package Main;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class DatosUsuario extends javax.swing.JFrame {
    static Pila usuariosEnSesion = new Pila();
    static int numUsuariosEnSesion=0;
    static boolean puedeCarro=true;
    int hCierre;
    public DatosUsuario() {
        initComponents();
        setVisible(true);
        setSize(488, 835); //Tamano de la ventana.
        setLocationRelativeTo(null); //Para que la ventana se ubique en el centro de la pantalla.
        jLabelCampObligatNombre1.setVisible(false);
        jLabelCampObligatNombre2.setVisible(false);
        jLabelCampObligatApellido1.setVisible(false);
        jLabelCampObligatApellido2.setVisible(false);
        jLabelCampObligatDocumento1.setVisible(false);
        jLabelCampObligatDocumento2.setVisible(false);
        jLabelCampObligatPlaca.setVisible(false);
        jLabelValNombre1.setVisible(false);
        jLabelValNombre2.setVisible(false);
        jLabelValApellido1.setVisible(false);
        jLabelValApellido2.setVisible(false);
        jLabelValDocumento1.setVisible(false);
        jLabelValDocumento2.setVisible(false);
        jLabelValPlaca.setVisible(false);
        jLabelTVehiculo.setVisible(false);
        jLabelMarca.setVisible(false);
        jLabelColor.setVisible(false);
        jLabelPlaca.setVisible(false);
        jComboNumAcompanantes.setVisible(false);
        jComboTVehiculo.setVisible(false);
        jComboMarca.setVisible(false);
        jComboColor.setVisible(false);
        jTextPlaca.setVisible(false);
        jLabelCAcompanantes1.setVisible(false);
        jLabelCAcompanantes2.setVisible(false);
        
        if (!puedeCarro){ //Los acompañantes no llevan carro
            jCheckVehiculo.setEnabled(false);
        }
        
        if(Bienvenido.diaActual.equals("Domingo")){
            hCierre = 20;
        } else{
            hCierre = 21;
        }
        for(int i=Bienvenido.horaActual; i<=hCierre; i++){
            jComboHSalida.addItem(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelNombre = new javax.swing.JLabel();
        LabelApellido = new javax.swing.JLabel();
        LabelDocumento = new javax.swing.JLabel();
        jComboTCI = new javax.swing.JComboBox<>();
        jTextNombre = new javax.swing.JTextField();
        jTextApellido = new javax.swing.JTextField();
        jTextDocumento = new javax.swing.JTextField();
        jCheckVehiculo = new javax.swing.JCheckBox();
        jComboTVehiculo = new javax.swing.JComboBox<>();
        jLabelTVehiculo = new javax.swing.JLabel();
        jLabelMarca = new javax.swing.JLabel();
        jComboMarca = new javax.swing.JComboBox<>();
        jLabelPlaca = new javax.swing.JLabel();
        jLabelColor = new javax.swing.JLabel();
        jTextPlaca = new javax.swing.JTextField();
        jComboColor = new javax.swing.JComboBox<>();
        jButtonAceptar = new javax.swing.JButton();
        jLabelCAcompanantes1 = new javax.swing.JLabel();
        jLabelCAcompanantes2 = new javax.swing.JLabel();
        jLabelValNombre1 = new javax.swing.JLabel();
        jLabelValApellido1 = new javax.swing.JLabel();
        jLabelValDocumento1 = new javax.swing.JLabel();
        jLabelValNombre2 = new javax.swing.JLabel();
        jLabelValApellido2 = new javax.swing.JLabel();
        jLabelValDocumento2 = new javax.swing.JLabel();
        jLabelCampObligatNombre1 = new javax.swing.JLabel();
        jLabelCampObligatNombre2 = new javax.swing.JLabel();
        jLabelCampObligatApellido1 = new javax.swing.JLabel();
        jLabelCampObligatApellido2 = new javax.swing.JLabel();
        jLabelCampObligatDocumento1 = new javax.swing.JLabel();
        jLabelCampObligatDocumento2 = new javax.swing.JLabel();
        jLabelCampObligatPlaca = new javax.swing.JLabel();
        jLabelValPlaca = new javax.swing.JLabel();
        jComboHSalida = new javax.swing.JComboBox<>();
        jComboMSalida = new javax.swing.JComboBox<>();
        text2 = new javax.swing.JLabel();
        jComboNumAcompanantes = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingrese sus datos");
        setResizable(false);
        getContentPane().setLayout(null);

        LabelNombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelNombre.setText("Primer Nombre:");
        getContentPane().add(LabelNombre);
        LabelNombre.setBounds(20, 30, 160, 22);

        LabelApellido.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelApellido.setText("Apellido:");
        getContentPane().add(LabelApellido);
        LabelApellido.setBounds(20, 110, 90, 22);

        LabelDocumento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelDocumento.setText("Documento:");
        getContentPane().add(LabelDocumento);
        LabelDocumento.setBounds(20, 190, 120, 22);

        jComboTCI.setBackground(new java.awt.Color(204, 255, 255));
        jComboTCI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboTCI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "V", "E", "J", "G" }));
        getContentPane().add(jComboTCI);
        jComboTCI.setBounds(20, 220, 50, 40);

        jTextNombre.setBackground(new java.awt.Color(204, 255, 255));
        jTextNombre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(jTextNombre);
        jTextNombre.setBounds(20, 60, 200, 40);

        jTextApellido.setBackground(new java.awt.Color(204, 255, 255));
        jTextApellido.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(jTextApellido);
        jTextApellido.setBounds(20, 140, 200, 40);

        jTextDocumento.setBackground(new java.awt.Color(204, 255, 255));
        jTextDocumento.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(jTextDocumento);
        jTextDocumento.setBounds(70, 220, 200, 40);

        jCheckVehiculo.setBackground(new java.awt.Color(204, 255, 255));
        jCheckVehiculo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckVehiculo.setText("Entré con vehículo.");
        jCheckVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckVehiculoActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckVehiculo);
        jCheckVehiculo.setBounds(30, 370, 210, 31);

        jComboTVehiculo.setBackground(new java.awt.Color(204, 255, 255));
        jComboTVehiculo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboTVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Camioneta (Pick-Up)", "Camioneta (Sport Wagon)", "Carro pequeño (2 puertas)", "Moto", "Sedan (4 puertas)" }));
        jComboTVehiculo.setEnabled(false);
        getContentPane().add(jComboTVehiculo);
        jComboTVehiculo.setBounds(190, 500, 230, 40);

        jLabelTVehiculo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTVehiculo.setText("Tipo de vehiculo:");
        getContentPane().add(jLabelTVehiculo);
        jLabelTVehiculo.setBounds(30, 510, 160, 22);

        jLabelMarca.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMarca.setText("Marca:");
        getContentPane().add(jLabelMarca);
        jLabelMarca.setBounds(120, 560, 70, 22);

        jComboMarca.setBackground(new java.awt.Color(204, 255, 255));
        jComboMarca.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboMarca.setMaximumRowCount(6);
        jComboMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aston Martin", "Audi", "Bera", "BMW", "Chery", "Chevrolet", "DFSK", "Empire Keeway", "Ferrari", "Fiat", "Ford", "Honda", "Hyundai", "Jeep", "Kawasaki", "Kia", "Lamborghini", "Mazda", "Mercedes-Benz", "Mitsubishi", "Nissan", "Peugeot", "Renault", "Seat", "Skygo", "Subaru", "Suzuki", "Tesla", "Toyota", "Vespa", "Volkswagen", "Yamaha", "Otro..." }));
        jComboMarca.setEnabled(false);
        getContentPane().add(jComboMarca);
        jComboMarca.setBounds(190, 550, 230, 40);

        jLabelPlaca.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelPlaca.setText("Placa:");
        getContentPane().add(jLabelPlaca);
        jLabelPlaca.setBounds(130, 660, 60, 22);

        jLabelColor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelColor.setText("Color:");
        getContentPane().add(jLabelColor);
        jLabelColor.setBounds(130, 610, 60, 22);

        jTextPlaca.setBackground(new java.awt.Color(204, 255, 255));
        jTextPlaca.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextPlaca.setEnabled(false);
        getContentPane().add(jTextPlaca);
        jTextPlaca.setBounds(190, 650, 200, 40);

        jComboColor.setBackground(new java.awt.Color(204, 255, 255));
        jComboColor.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboColor.setMaximumRowCount(4);
        jComboColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amarillo", "Azul", "Blanco", "Gris", "Marrón", "Morado", "Naranja", "Negro", "Plateado", "Rojo", "Rosa", "Verde" }));
        jComboColor.setEnabled(false);
        getContentPane().add(jComboColor);
        jComboColor.setBounds(190, 600, 200, 40);

        jButtonAceptar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAceptar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAceptar);
        jButtonAceptar.setBounds(180, 720, 130, 60);

        jLabelCAcompanantes1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCAcompanantes1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelCAcompanantes1.setText("Número de acompañantes");
        jLabelCAcompanantes1.setToolTipText("");
        jLabelCAcompanantes1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabelCAcompanantes1);
        jLabelCAcompanantes1.setBounds(40, 430, 250, 30);

        jLabelCAcompanantes2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelCAcompanantes2.setText("en el vehículo:");
        getContentPane().add(jLabelCAcompanantes2);
        jLabelCAcompanantes2.setBounds(150, 450, 140, 30);

        jLabelValNombre1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelValNombre1.setForeground(new java.awt.Color(255, 0, 0));
        jLabelValNombre1.setText("  * SOLO SE PERMITEN");
        getContentPane().add(jLabelValNombre1);
        jLabelValNombre1.setBounds(220, 60, 170, 20);

        jLabelValApellido1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelValApellido1.setForeground(new java.awt.Color(255, 0, 0));
        jLabelValApellido1.setText("  * SOLO SE PERMITEN");
        getContentPane().add(jLabelValApellido1);
        jLabelValApellido1.setBounds(220, 140, 170, 20);

        jLabelValDocumento1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelValDocumento1.setForeground(new java.awt.Color(255, 0, 0));
        jLabelValDocumento1.setText("  * SOLO SE PERMITEN");
        getContentPane().add(jLabelValDocumento1);
        jLabelValDocumento1.setBounds(270, 220, 170, 20);

        jLabelValNombre2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelValNombre2.setForeground(new java.awt.Color(255, 0, 0));
        jLabelValNombre2.setText("LETRAS.");
        getContentPane().add(jLabelValNombre2);
        jLabelValNombre2.setBounds(240, 80, 59, 17);

        jLabelValApellido2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelValApellido2.setForeground(new java.awt.Color(255, 0, 0));
        jLabelValApellido2.setText("LETRAS.");
        getContentPane().add(jLabelValApellido2);
        jLabelValApellido2.setBounds(240, 160, 59, 17);

        jLabelValDocumento2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelValDocumento2.setForeground(new java.awt.Color(255, 0, 0));
        jLabelValDocumento2.setText("NUMEROS.");
        getContentPane().add(jLabelValDocumento2);
        jLabelValDocumento2.setBounds(290, 240, 80, 20);

        jLabelCampObligatNombre1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCampObligatNombre1.setForeground(new java.awt.Color(255, 0, 0));
        jLabelCampObligatNombre1.setText("  *EL CAMPO ES ");
        getContentPane().add(jLabelCampObligatNombre1);
        jLabelCampObligatNombre1.setBounds(220, 60, 140, 20);

        jLabelCampObligatNombre2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCampObligatNombre2.setForeground(new java.awt.Color(255, 0, 0));
        jLabelCampObligatNombre2.setText("OBLIGATORIO.");
        getContentPane().add(jLabelCampObligatNombre2);
        jLabelCampObligatNombre2.setBounds(240, 80, 110, 20);

        jLabelCampObligatApellido1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCampObligatApellido1.setForeground(new java.awt.Color(255, 0, 0));
        jLabelCampObligatApellido1.setText("  * EL CAMPO ES ");
        getContentPane().add(jLabelCampObligatApellido1);
        jLabelCampObligatApellido1.setBounds(220, 140, 120, 17);

        jLabelCampObligatApellido2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCampObligatApellido2.setForeground(new java.awt.Color(255, 0, 0));
        jLabelCampObligatApellido2.setText("OBLIGATORIO.");
        getContentPane().add(jLabelCampObligatApellido2);
        jLabelCampObligatApellido2.setBounds(240, 160, 120, 14);

        jLabelCampObligatDocumento1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCampObligatDocumento1.setForeground(new java.awt.Color(255, 0, 0));
        jLabelCampObligatDocumento1.setText("  * EL CAMPO ES ");
        getContentPane().add(jLabelCampObligatDocumento1);
        jLabelCampObligatDocumento1.setBounds(270, 220, 120, 17);

        jLabelCampObligatDocumento2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCampObligatDocumento2.setForeground(new java.awt.Color(255, 0, 0));
        jLabelCampObligatDocumento2.setText("OBLIGATORIO.");
        getContentPane().add(jLabelCampObligatDocumento2);
        jLabelCampObligatDocumento2.setBounds(290, 240, 120, 17);

        jLabelCampObligatPlaca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCampObligatPlaca.setForeground(new java.awt.Color(255, 0, 0));
        jLabelCampObligatPlaca.setText(" *EL CAMPO ES OBLIGATORIO.");
        getContentPane().add(jLabelCampObligatPlaca);
        jLabelCampObligatPlaca.setBounds(190, 690, 230, 20);

        jLabelValPlaca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelValPlaca.setForeground(new java.awt.Color(255, 0, 0));
        jLabelValPlaca.setText(" *SOLO SE PERMITEN LETRAS MAYUS Y NUMEROS.");
        getContentPane().add(jLabelValPlaca);
        jLabelValPlaca.setBounds(120, 690, 370, 20);

        jComboHSalida.setBackground(new java.awt.Color(204, 255, 255));
        jComboHSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboHSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(jComboHSalida);
        jComboHSalida.setBounds(210, 310, 60, 40);

        jComboMSalida.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(jComboMSalida);
        jComboMSalida.setBounds(300, 310, 60, 40);

        text2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text2.setText(":");
        getContentPane().add(text2);
        text2.setBounds(280, 320, 10, 16);

        jComboNumAcompanantes.setBackground(new java.awt.Color(204, 255, 255));
        jComboNumAcompanantes.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jComboNumAcompanantes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        getContentPane().add(jComboNumAcompanantes);
        jComboNumAcompanantes.setBounds(290, 440, 60, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Indique su hora");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 300, 150, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("de salida:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 320, 100, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoCostazul2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 490, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckVehiculoActionPerformed
        if (jCheckVehiculo.isSelected()){
            jLabelTVehiculo.setVisible(true);
            jLabelMarca.setVisible(true);
            jLabelColor.setVisible(true);
            jLabelPlaca.setVisible(true);
            jComboNumAcompanantes.setVisible(true);
            jComboNumAcompanantes.setEnabled(true);
            jComboTVehiculo.setVisible(true);
            jComboTVehiculo.setEnabled(true);
            jComboMarca.setVisible(true);
            jComboMarca.setEnabled(true);
            jComboColor.setVisible(true);
            jComboColor.setEnabled(true);
            jTextPlaca.setVisible(true);
            jTextPlaca.setEnabled(true);
            jLabelCAcompanantes1.setVisible(true);
            jLabelCAcompanantes2.setVisible(true);
        } else{
            jLabelTVehiculo.setVisible(false);
            jLabelMarca.setVisible(false);
            jLabelColor.setVisible(false);
            jLabelPlaca.setVisible(false);
            jComboNumAcompanantes.setVisible(false);
            jComboNumAcompanantes.setEnabled(false);
            jComboTVehiculo.setVisible(false);
            jComboTVehiculo.setEnabled(false);
            jComboMarca.setVisible(false);
            jComboMarca.setEnabled(false);
            jComboColor.setVisible(false);
            jComboColor.setEnabled(false);
            jTextPlaca.setVisible(false);
            jTextPlaca.setEnabled(false);
            jLabelCAcompanantes1.setVisible(false);
            jLabelCAcompanantes2.setVisible(false);
            jLabelCampObligatPlaca.setVisible(false);
        }
    }//GEN-LAST:event_jCheckVehiculoActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed

        //verificamos que el nombre solo contenga letras y no permita que el campo quede vacio
        if (jTextNombre.getText().isEmpty()){ //METODO PARA VERIFICAR QUE LA CADENA SE ENCUENTRE VACIA
            jLabelCampObligatNombre1.setVisible(true);
            jLabelCampObligatNombre2.setVisible(true);
        } else{
            jLabelCampObligatNombre1.setVisible(false);
            jLabelCampObligatNombre2.setVisible(false);
                
            if (!jTextNombre.getText().matches("^[a-zA-Z]+$")){
                jLabelValNombre1.setVisible(true);
                jLabelValNombre2.setVisible(true);
            } else {
                jLabelValNombre1.setVisible(false);
                jLabelValNombre2.setVisible(false);
            }
        }
        
        //verificamos que el apellido solo contenga letras y no permita que el campo quede vacio
        if (jTextApellido.getText().isEmpty()){ //METODO PARA VERIFICAR QUE LA CADENA SE ENCUENTRE VACIA
            jLabelCampObligatApellido1.setVisible(true);
            jLabelCampObligatApellido2.setVisible(true);
        } else{
            jLabelCampObligatApellido1.setVisible(false);
            jLabelCampObligatApellido2.setVisible(false);
            
            if(!jTextApellido.getText().matches("^[a-zA-Z]+$")){
                jLabelValApellido1.setVisible(true);
                jLabelValApellido2.setVisible(true);
            } else{
                jLabelValApellido1.setVisible(false);
                jLabelValApellido2.setVisible(false);
            }
        }
        
        //verificamos que el documento(cedula) solo contenga numeros y no permita que el campo quede vacio
        if (jTextDocumento.getText().isEmpty()){ //METODO PARA VERIFICAR QUE LA CADENA SE ENCUENTRE VACIA
            jLabelCampObligatDocumento1.setVisible(true);
            jLabelCampObligatDocumento2.setVisible(true);
        } else{
            jLabelCampObligatDocumento1.setVisible(false);
            jLabelCampObligatDocumento2.setVisible(false);
            
            if(!jTextDocumento.getText().matches("^[0-9]+$")){
                jLabelValDocumento1.setVisible(true);
                jLabelValDocumento2.setVisible(true);
            } else{
                jLabelValDocumento1.setVisible(false);
                jLabelValDocumento2.setVisible(false);
            }
        }
        
        //verificamos que la placa del carro solo contenga numeros y letras, y  no permita que el campo quede vacio
       if (jCheckVehiculo.isSelected()){
            if (jTextPlaca.getText().isEmpty()){
                jLabelCampObligatPlaca.setVisible(true);
            } else{
                jLabelCampObligatPlaca.setVisible(false);
                if (!jTextPlaca.getText().matches("^[A-Z0-9]*$")){
                     jLabelValPlaca.setVisible(true);
                } else{
                     jLabelValPlaca.setVisible(false);
                }
            }
       }
        
  
        if (jTextNombre.getText().matches("^[a-zA-Z]+$") && jTextApellido.getText().matches("^[a-zA-Z]+$") && jTextDocumento.getText().matches("^[0-9]+$") && jTextPlaca.getText().matches("^[A-Z0-9]*$")){
            usuariosEnSesion.agregarPersonaEnLaPila(new Persona(Bienvenido.idPersona, jTextNombre.getText(), jTextApellido.getText(), jComboTCI.getSelectedItem().toString(), jTextDocumento.getText(), Bienvenido.diaActual, Bienvenido.horaActual, Bienvenido.minActual, Integer.parseInt(jComboHSalida.getSelectedItem().toString()), Integer.parseInt(jComboMSalida.getSelectedItem().toString())));
            Bienvenido.idPersona++;
            if (jCheckVehiculo.isSelected()){
                numUsuariosEnSesion=Integer.parseInt(jComboNumAcompanantes.getSelectedItem().toString())+1;
                usuariosEnSesion.verTope().setCarro(new Vehiculo(usuariosEnSesion.verTope(), jComboTVehiculo.getSelectedItem().toString(), jTextPlaca.getText(), jComboColor.getSelectedItem().toString(), jComboMarca.getSelectedItem().toString()));
                dispose();
                vEstacionamiento VE = new vEstacionamiento();
            } else{
                if (jCheckVehiculo.isEnabled()){
                    numUsuariosEnSesion=1;
                }
                usuariosEnSesion.verTope().setCarro(null);
                int c=JOptionPane.showConfirmDialog(this, "¿Desea realizar una compra?", "Seleccione una opción:", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                dispose();
                if (c==0){
                    vCompras VC = new vCompras();
                } else if (usuariosEnSesion.getTamanio()<numUsuariosEnSesion){
                    puedeCarro=false;
                    DatosUsuario DU = new DatosUsuario();
                } else{
                    puedeCarro=true;
                    while (!DatosUsuario.usuariosEnSesion.esVacia()){
                        Bienvenido.personas.insertarPersona(DatosUsuario.usuariosEnSesion.sacarPersonaDePila());
                    }
                    try {
                        Bienvenido B = new Bienvenido();
                        B.setVisible(true);
                    } catch (IOException ex) {
                        Logger.getLogger(DatosUsuario.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jComboHSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboHSalidaActionPerformed
        jComboMSalida.removeAllItems();
        if (Integer.parseInt(jComboHSalida.getSelectedItem().toString())==Bienvenido.horaActual){
            for (int i=Bienvenido.minActual; i<=59; i++){
                if (i<10){
                    jComboMSalida.addItem("0" + i);
                } else{
                    jComboMSalida.addItem(String.valueOf(i));
                }
            }
        } else if (Integer.parseInt(jComboHSalida.getSelectedItem().toString())==hCierre){
            jComboMSalida.addItem("00");
        } else{
            for (int i=0; i<=59; i++){
                if (i<10){
                    jComboMSalida.addItem("0" + i);
                } else{
                    jComboMSalida.addItem(String.valueOf(i));
                }
            }
        }
    }//GEN-LAST:event_jComboHSalidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelApellido;
    private javax.swing.JLabel LabelDocumento;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JCheckBox jCheckVehiculo;
    private javax.swing.JComboBox<String> jComboColor;
    private javax.swing.JComboBox<Integer> jComboHSalida;
    private javax.swing.JComboBox<String> jComboMSalida;
    private javax.swing.JComboBox<String> jComboMarca;
    private javax.swing.JComboBox<String> jComboNumAcompanantes;
    private javax.swing.JComboBox<String> jComboTCI;
    private javax.swing.JComboBox<String> jComboTVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCAcompanantes1;
    private javax.swing.JLabel jLabelCAcompanantes2;
    private javax.swing.JLabel jLabelCampObligatApellido1;
    private javax.swing.JLabel jLabelCampObligatApellido2;
    private javax.swing.JLabel jLabelCampObligatDocumento1;
    private javax.swing.JLabel jLabelCampObligatDocumento2;
    private javax.swing.JLabel jLabelCampObligatNombre1;
    private javax.swing.JLabel jLabelCampObligatNombre2;
    private javax.swing.JLabel jLabelCampObligatPlaca;
    private javax.swing.JLabel jLabelColor;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JLabel jLabelTVehiculo;
    private javax.swing.JLabel jLabelValApellido1;
    private javax.swing.JLabel jLabelValApellido2;
    private javax.swing.JLabel jLabelValDocumento1;
    private javax.swing.JLabel jLabelValDocumento2;
    private javax.swing.JLabel jLabelValNombre1;
    private javax.swing.JLabel jLabelValNombre2;
    private javax.swing.JLabel jLabelValPlaca;
    private javax.swing.JTextField jTextApellido;
    private javax.swing.JTextField jTextDocumento;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextPlaca;
    private javax.swing.JLabel text2;
    // End of variables declaration//GEN-END:variables
}
