/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class menuEditar extends javax.swing.JFrame {
    
    static Pila coincidencias;
    Persona[] arrayPersonas;
    Persona p;
    puestoEst puesto;
    Compra[] compras;
    Producto[] productos;
    public menuEditar() {
        coincidencias = new Pila();
        initComponents();
        setVisible(true);
        setSize(916, 575); //Tamano de la ventana.
        setLocationRelativeTo(null); //Para que la ventana se ubique en el centro de la pantalla.
        jPanelBorrar.setVisible(false);
        jButtonEliminar.setVisible(false);
        jButtonConfirmarC.setVisible(false);
        jPanelOcupado.setVisible(false);
        jRadioButtonNombreApellido.setSelected(true);
        jLabelDocumento.setVisible(false);
        jLabelDia.setVisible(false);
        jComboDia.setVisible(false);
        jComboDia.setEnabled(false);
        jPanelCoincidencia.setVisible(false);
        jComboCoincidencias.setVisible(false);
        jComboTCI.setVisible(false);
        jLabelHEntrada1.setVisible(false);
        jLabelHEntrada2.setVisible(false);
        jComboHEntrada.setVisible(false);
        jComboMEntrada.setVisible(false);
        jLabelNombre.setVisible(false);
        jLabelApellido.setVisible(false);
        jTextFieldNombre.setVisible(false);
        jTextFieldApellido.setVisible(false);
        jComboBoxTCI.setVisible(false);
        jTextFieldCI.setVisible(false);
        jLabelHSalida1.setVisible(false);
        jLabelHSalida2.setVisible(false);
        jComboHSalida.setVisible(false);
        jComboMSalida.setVisible(false);
        jCheckBoxVehiculo.setVisible(false);
        jLabelTVehiculo1.setVisible(false);
        jLabelTVehiculo2.setVisible(false);
        jLabel1.setVisible(false);
        jLabel3.setVisible(false);
        jLabel6.setVisible(false);
        jComboTVehiculo.setVisible(false);
        jLabelMarca.setVisible(false);
        jComboMarca.setVisible(false);
        jLabelColor.setVisible(false);
        jComboColor.setVisible(false);
        jLabelPlaca.setVisible(false);
        jTextFieldPlaca.setVisible(false);
        jLabelPuesto.setVisible(false);
        jComboSector.setVisible(false);
        jComboNPuesto.setVisible(false);
        ActionListener[] tiendas = jComboTiendas.getActionListeners();
        jComboTiendas.removeActionListener(tiendas[0]);
        for(int i=0; i<Bienvenido.nombresTiendas.length; i++){
            jComboTiendas.addItem(Bienvenido.nombresTiendas[i]);
        }
        jComboTiendas.addActionListener(tiendas[0]);
        jComboCompra.setVisible(false);
        jComboTiendas.setVisible(false);
        jComboProductos.setVisible(false);
        jLabelTotal.setVisible(false);
        jTextUnidades.setVisible(false);
        jRadioButtonOnline.setVisible(false);
        jRadioButtonPresencial.setVisible(false);
        jLabelPrecio.setVisible(false);
        jComboMetodoPago.setVisible(false);
        jLabelNCompra.setVisible(false);
        jLabelTienda.setVisible(false);
        jLabelProducto.setVisible(false);
        jLabelMPago.setVisible(false);
        jLabelUnidades.setVisible(false);
        jLabelTCompra.setVisible(false);
    }
    
    public puestoEst encontrarPuesto(Persona persona){ //Para conseguir el puesto que esta siendo usada por la persona
        for(int i=0; i<5; i++){
            for(int j=0; j<500; j++){
                if(Bienvenido.sectoresCarros[i][j].getOcupantes().existeOcupante(persona)){
                    return Bienvenido.sectoresCarros[i][j];
                }
            }
        }
        
        for(int i=0; i<2; i++){
            for(int j=0; j<100; j++){
                if(Bienvenido.sectoresMotos[i][j].getOcupantes().existeOcupante(persona)){
                    return Bienvenido.sectoresMotos[i][j];
                }
            }
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanelBorrar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextBuscar1 = new javax.swing.JTextField();
        jComboTCI = new javax.swing.JComboBox<>();
        jComboCoincidencias = new javax.swing.JComboBox<>();
        jTextBuscar2 = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jRadioButtonNombreApellido = new javax.swing.JRadioButton();
        jRadioButtonDocumento = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelBNombre = new javax.swing.JLabel();
        jLabelBApellido = new javax.swing.JLabel();
        jComboBoxTCI = new javax.swing.JComboBox<>();
        jTextFieldCI = new javax.swing.JTextField();
        jComboHSalida = new javax.swing.JComboBox<>();
        jComboMSalida = new javax.swing.JComboBox<>();
        jComboSector = new javax.swing.JComboBox<>();
        jComboNPuesto = new javax.swing.JComboBox<>();
        jLabelHSalida1 = new javax.swing.JLabel();
        jLabelPuesto = new javax.swing.JLabel();
        jComboHEntrada = new javax.swing.JComboBox<>();
        jComboMEntrada = new javax.swing.JComboBox<>();
        jLabelHEntrada1 = new javax.swing.JLabel();
        jComboTVehiculo = new javax.swing.JComboBox<>();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jCheckBoxVehiculo = new javax.swing.JCheckBox();
        jLabelTVehiculo1 = new javax.swing.JLabel();
        jComboMarca = new javax.swing.JComboBox<>();
        jLabelMarca = new javax.swing.JLabel();
        jLabelColor = new javax.swing.JLabel();
        jComboColor = new javax.swing.JComboBox<>();
        jTextFieldPlaca = new javax.swing.JTextField();
        jLabelPlaca = new javax.swing.JLabel();
        jLabelHEntrada2 = new javax.swing.JLabel();
        jLabelHSalida2 = new javax.swing.JLabel();
        jLabelDia = new javax.swing.JLabel();
        jComboDia = new javax.swing.JComboBox<>();
        jButtonCancel = new javax.swing.JButton();
        jComboTiendas = new javax.swing.JComboBox<>();
        jComboCompra = new javax.swing.JComboBox<>();
        jComboProductos = new javax.swing.JComboBox<>();
        jTextUnidades = new javax.swing.JTextField();
        jLabelTotal = new javax.swing.JLabel();
        jRadioButtonOnline = new javax.swing.JRadioButton();
        jRadioButtonPresencial = new javax.swing.JRadioButton();
        jComboMetodoPago = new javax.swing.JComboBox<>();
        jLabelPrecio = new javax.swing.JLabel();
        jButtonConfirmarC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelDocumento = new javax.swing.JLabel();
        jLabelTVehiculo2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelNCompra = new javax.swing.JLabel();
        jLabelTienda = new javax.swing.JLabel();
        jLabelProducto = new javax.swing.JLabel();
        jLabelTCompra = new javax.swing.JLabel();
        jLabelUnidades = new javax.swing.JLabel();
        jLabelMPago = new javax.swing.JLabel();
        jPanelCoincidencia = new javax.swing.JPanel();
        jLabelCoincidencia = new javax.swing.JLabel();
        jPanelOcupado = new javax.swing.JPanel();
        pOcupado = new javax.swing.JLabel();
        jButtonEliminar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editar informacion de persona");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanelBorrar.setBackground(new java.awt.Color(204, 255, 255));
        jPanelBorrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 102), 5, true));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Persona");
        jPanelBorrar.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("borrada");
        jPanelBorrar.add(jLabel5);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("exitosamente");
        jPanelBorrar.add(jLabel7);

        getContentPane().add(jPanelBorrar);
        jPanelBorrar.setBounds(310, 220, 260, 90);

        jTextBuscar1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(jTextBuscar1);
        jTextBuscar1.setBounds(410, 40, 138, 30);

        jComboTCI.setBackground(new java.awt.Color(204, 255, 255));
        jComboTCI.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jComboTCI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "V", "E", "J", "G" }));
        jComboTCI.setEnabled(false);
        getContentPane().add(jComboTCI);
        jComboTCI.setBounds(360, 40, 50, 30);

        jComboCoincidencias.setBackground(new java.awt.Color(204, 255, 255));
        jComboCoincidencias.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jComboCoincidencias.setEnabled(false);
        jComboCoincidencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCoincidenciasActionPerformed(evt);
            }
        });
        getContentPane().add(jComboCoincidencias);
        jComboCoincidencias.setBounds(400, 83, 180, 40);

        jTextBuscar2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(jTextBuscar2);
        jTextBuscar2.setBounds(650, 40, 140, 30);

        jTextFieldNombre.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextFieldNombre.setEnabled(false);
        getContentPane().add(jTextFieldNombre);
        jTextFieldNombre.setBounds(110, 230, 170, 30);

        jTextFieldApellido.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextFieldApellido.setEnabled(false);
        getContentPane().add(jTextFieldApellido);
        jTextFieldApellido.setBounds(110, 280, 170, 30);

        jButtonBuscar.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar);
        jButtonBuscar.setBounds(800, 40, 90, 30);

        buttonGroup1.add(jRadioButtonNombreApellido);
        jRadioButtonNombreApellido.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jRadioButtonNombreApellido.setText("Nombre y apellido");
        jRadioButtonNombreApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNombreApellidoActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonNombreApellido);
        jRadioButtonNombreApellido.setBounds(30, 40, 160, 29);

        buttonGroup1.add(jRadioButtonDocumento);
        jRadioButtonDocumento.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jRadioButtonDocumento.setText("Documento");
        jRadioButtonDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDocumentoActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonDocumento);
        jRadioButtonDocumento.setBounds(200, 40, 120, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Buscar por:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 10, 110, 22);

        jLabelBNombre.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelBNombre.setText("Nombre:");
        getContentPane().add(jLabelBNombre);
        jLabelBNombre.setBounds(330, 40, 80, 30);

        jLabelBApellido.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelBApellido.setText("Apellido:");
        getContentPane().add(jLabelBApellido);
        jLabelBApellido.setBounds(570, 40, 80, 30);

        jComboBoxTCI.setBackground(new java.awt.Color(204, 255, 255));
        jComboBoxTCI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "V", "E", "J", "G" }));
        jComboBoxTCI.setEnabled(false);
        getContentPane().add(jComboBoxTCI);
        jComboBoxTCI.setBounds(60, 360, 50, 30);

        jTextFieldCI.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextFieldCI.setEnabled(false);
        getContentPane().add(jTextFieldCI);
        jTextFieldCI.setBounds(110, 360, 170, 30);

        jComboHSalida.setBackground(new java.awt.Color(204, 255, 255));
        jComboHSalida.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jComboHSalida.setEnabled(false);
        jComboHSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboHSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(jComboHSalida);
        jComboHSalida.setBounds(110, 410, 50, 30);

        jComboMSalida.setBackground(new java.awt.Color(204, 255, 255));
        jComboMSalida.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jComboMSalida.setEnabled(false);
        getContentPane().add(jComboMSalida);
        jComboMSalida.setBounds(190, 410, 50, 30);

        jComboSector.setBackground(new java.awt.Color(204, 255, 255));
        jComboSector.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jComboSector.setEnabled(false);
        jComboSector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboSectorActionPerformed(evt);
            }
        });
        getContentPane().add(jComboSector);
        jComboSector.setBounds(540, 290, 50, 30);

        jComboNPuesto.setBackground(new java.awt.Color(204, 255, 255));
        jComboNPuesto.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jComboNPuesto.setEnabled(false);
        getContentPane().add(jComboNPuesto);
        jComboNPuesto.setBounds(620, 290, 50, 30);

        jLabelHSalida1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelHSalida1.setText("Hora de");
        getContentPane().add(jLabelHSalida1);
        jLabelHSalida1.setBounds(30, 410, 60, 19);

        jLabelPuesto.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelPuesto.setText("Puesto:");
        getContentPane().add(jLabelPuesto);
        jLabelPuesto.setBounds(470, 290, 60, 30);

        jComboHEntrada.setBackground(new java.awt.Color(204, 255, 255));
        jComboHEntrada.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jComboHEntrada.setEnabled(false);
        jComboHEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboHEntradaActionPerformed(evt);
            }
        });
        getContentPane().add(jComboHEntrada);
        jComboHEntrada.setBounds(110, 180, 50, 30);

        jComboMEntrada.setBackground(new java.awt.Color(204, 255, 255));
        jComboMEntrada.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jComboMEntrada.setEnabled(false);
        jComboMEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboMEntradaActionPerformed(evt);
            }
        });
        getContentPane().add(jComboMEntrada);
        jComboMEntrada.setBounds(190, 180, 50, 30);

        jLabelHEntrada1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelHEntrada1.setText("Hora de");
        getContentPane().add(jLabelHEntrada1);
        jLabelHEntrada1.setBounds(40, 175, 60, 16);

        jComboTVehiculo.setBackground(new java.awt.Color(204, 255, 255));
        jComboTVehiculo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jComboTVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Camioneta (Pick-Up)", "Camioneta (Sport Wagon)", "Carro pequeño (2 puertas)", "Moto", "Sedan (4 puertas)" }));
        jComboTVehiculo.setEnabled(false);
        jComboTVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTVehiculoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboTVehiculo);
        jComboTVehiculo.setBounds(530, 190, 180, 30);

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelNombre.setText("Nombre:");
        getContentPane().add(jLabelNombre);
        jLabelNombre.setBounds(30, 229, 70, 30);

        jLabelApellido.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelApellido.setText("Apellido:");
        getContentPane().add(jLabelApellido);
        jLabelApellido.setBounds(30, 280, 70, 19);

        jCheckBoxVehiculo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jCheckBoxVehiculo.setText("Posee Vehiculo.");
        jCheckBoxVehiculo.setEnabled(false);
        jCheckBoxVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxVehiculoActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxVehiculo);
        jCheckBoxVehiculo.setBounds(460, 140, 160, 29);

        jLabelTVehiculo1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelTVehiculo1.setText("Tipo de");
        getContentPane().add(jLabelTVehiculo1);
        jLabelTVehiculo1.setBounds(460, 180, 60, 19);

        jComboMarca.setBackground(new java.awt.Color(204, 255, 255));
        jComboMarca.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aston Martin", "Audi", "Bera", "BMW", "Chery", "Chevrolet", "DFSK", "Empire Keeway", "Ferrari", "Fiat", "Ford", "Honda", "Hyundai", "Jeep", "Kawasaki", "Kia", "Lamborghini", "Mazda", "Mercedes-Benz", "Mitsubishi", "Nissan", "Peugeot", "Renault", "Seat", "Skygo", "Subaru", "Suzuki", "Tesla", "Toyota", "Vespa", "Volkswagen", "Yamaha", "Otro..." }));
        jComboMarca.setEnabled(false);
        getContentPane().add(jComboMarca);
        jComboMarca.setBounds(740, 190, 130, 30);

        jLabelMarca.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelMarca.setText("Marca:");
        getContentPane().add(jLabelMarca);
        jLabelMarca.setBounds(740, 160, 60, 19);

        jLabelColor.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelColor.setText("Color:");
        getContentPane().add(jLabelColor);
        jLabelColor.setBounds(470, 240, 50, 19);

        jComboColor.setBackground(new java.awt.Color(204, 255, 255));
        jComboColor.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jComboColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amarillo", "Azul", "Blanco", "Gris", "Marrón", "Morado", "Naranja", "Negro", "Plateado", "Rojo", "Rosa", "Verde" }));
        jComboColor.setEnabled(false);
        getContentPane().add(jComboColor);
        jComboColor.setBounds(530, 240, 110, 30);

        jTextFieldPlaca.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextFieldPlaca.setEnabled(false);
        getContentPane().add(jTextFieldPlaca);
        jTextFieldPlaca.setBounds(730, 240, 140, 30);

        jLabelPlaca.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelPlaca.setText("Placa:");
        getContentPane().add(jLabelPlaca);
        jLabelPlaca.setBounds(670, 240, 50, 30);

        jLabelHEntrada2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelHEntrada2.setText("entrada:");
        getContentPane().add(jLabelHEntrada2);
        jLabelHEntrada2.setBounds(30, 195, 70, 19);

        jLabelHSalida2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelHSalida2.setText("salida:");
        getContentPane().add(jLabelHSalida2);
        jLabelHSalida2.setBounds(40, 430, 50, 19);

        jLabelDia.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelDia.setText("Dia:");
        getContentPane().add(jLabelDia);
        jLabelDia.setBounds(60, 135, 40, 19);

        jComboDia.setBackground(new java.awt.Color(204, 255, 255));
        jComboDia.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jComboDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo" }));
        jComboDia.setEnabled(false);
        jComboDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboDiaActionPerformed(evt);
            }
        });
        getContentPane().add(jComboDia);
        jComboDia.setBounds(110, 130, 130, 30);

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonCancel.setText("Cancelar");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancel);
        jButtonCancel.setBounds(20, 480, 110, 40);

        jComboTiendas.setBackground(new java.awt.Color(204, 255, 255));
        jComboTiendas.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jComboTiendas.setEnabled(false);
        jComboTiendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTiendasActionPerformed(evt);
            }
        });
        getContentPane().add(jComboTiendas);
        jComboTiendas.setBounds(550, 360, 150, 30);

        jComboCompra.setBackground(new java.awt.Color(204, 255, 255));
        jComboCompra.setEnabled(false);
        jComboCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCompraActionPerformed(evt);
            }
        });
        getContentPane().add(jComboCompra);
        jComboCompra.setBounds(480, 360, 50, 30);

        jComboProductos.setBackground(new java.awt.Color(204, 255, 255));
        jComboProductos.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jComboProductos.setEnabled(false);
        jComboProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboProductosActionPerformed(evt);
            }
        });
        getContentPane().add(jComboProductos);
        jComboProductos.setBounds(720, 360, 160, 30);

        jTextUnidades.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextUnidades.setEnabled(false);
        jTextUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUnidadesActionPerformed(evt);
            }
        });
        getContentPane().add(jTextUnidades);
        jTextUnidades.setBounds(810, 450, 50, 30);

        jLabelTotal.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelTotal.setText("Total:");
        getContentPane().add(jLabelTotal);
        jLabelTotal.setBounds(470, 440, 170, 19);

        buttonGroup2.add(jRadioButtonOnline);
        jRadioButtonOnline.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jRadioButtonOnline.setText("Online");
        jRadioButtonOnline.setEnabled(false);
        jRadioButtonOnline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonOnlineActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonOnline);
        jRadioButtonOnline.setBounds(470, 500, 80, 27);

        buttonGroup2.add(jRadioButtonPresencial);
        jRadioButtonPresencial.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jRadioButtonPresencial.setText("Presencial");
        jRadioButtonPresencial.setEnabled(false);
        jRadioButtonPresencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPresencialActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonPresencial);
        jRadioButtonPresencial.setBounds(550, 500, 100, 27);

        jComboMetodoPago.setBackground(new java.awt.Color(204, 255, 255));
        jComboMetodoPago.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jComboMetodoPago.setMaximumRowCount(3);
        jComboMetodoPago.setEnabled(false);
        jComboMetodoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboMetodoPagoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboMetodoPago);
        jComboMetodoPago.setBounds(650, 450, 120, 30);

        jLabelPrecio.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelPrecio.setText("Precio:");
        getContentPane().add(jLabelPrecio);
        jLabelPrecio.setBounds(470, 410, 160, 19);

        jButtonConfirmarC.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonConfirmarC.setText("Confirmar cambios");
        jButtonConfirmarC.setEnabled(false);
        jButtonConfirmarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarCActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirmarC);
        jButtonConfirmarC.setBounds(140, 480, 190, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(":");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 185, 10, 16);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(":");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 415, 10, 16);

        jLabelDocumento.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelDocumento.setText("Documento:");
        getContentPane().add(jLabelDocumento);
        jLabelDocumento.setBounds(20, 330, 100, 19);

        jLabelTVehiculo2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelTVehiculo2.setText("vehiculo:");
        getContentPane().add(jLabelTVehiculo2);
        jLabelTVehiculo2.setBounds(450, 200, 70, 19);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("-");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(590, 290, 30, 30);

        jLabelNCompra.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelNCompra.setText("N° Compra:");
        getContentPane().add(jLabelNCompra);
        jLabelNCompra.setBounds(440, 330, 90, 19);

        jLabelTienda.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelTienda.setText("Tienda:");
        getContentPane().add(jLabelTienda);
        jLabelTienda.setBounds(550, 330, 60, 19);

        jLabelProducto.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelProducto.setText("Producto:");
        getContentPane().add(jLabelProducto);
        jLabelProducto.setBounds(720, 330, 80, 19);

        jLabelTCompra.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelTCompra.setText("Tipo de compra:");
        getContentPane().add(jLabelTCompra);
        jLabelTCompra.setBounds(470, 470, 130, 19);

        jLabelUnidades.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelUnidades.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUnidades.setText("Unidades:");
        getContentPane().add(jLabelUnidades);
        jLabelUnidades.setBounds(800, 420, 80, 30);

        jLabelMPago.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelMPago.setText("Metodo de pago:");
        getContentPane().add(jLabelMPago);
        jLabelMPago.setBounds(650, 420, 130, 30);

        jPanelCoincidencia.setBackground(new java.awt.Color(204, 255, 255));
        jPanelCoincidencia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 102), 3, true));

        jLabelCoincidencia.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelCoincidencia.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanelCoincidencia.add(jLabelCoincidencia);

        getContentPane().add(jPanelCoincidencia);
        jPanelCoincidencia.setBounds(30, 83, 360, 40);

        jPanelOcupado.setBackground(new java.awt.Color(204, 255, 255));
        jPanelOcupado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 102), 3, true));

        pOcupado.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        pOcupado.setForeground(new java.awt.Color(255, 0, 51));
        pOcupado.setText("Puesto ocupado");
        jPanelOcupado.add(pOcupado);

        getContentPane().add(jPanelOcupado);
        jPanelOcupado.setBounds(690, 280, 150, 40);

        jButtonEliminar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.setEnabled(false);
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminar);
        jButtonEliminar.setBounds(340, 480, 100, 40);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoCostazul4.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 916, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        boolean valido = false;
        if(jRadioButtonNombreApellido.isSelected()){
            if(jTextBuscar1.getText().matches("^[a-zA-Z]+$") && jTextBuscar2.getText().matches("^[a-zA-Z]+$")){
                valido = true;
                jTextBuscar1.setForeground(Color.black);
                jTextBuscar2.setForeground(Color.black);
            } else {
                if(!jTextBuscar1.getText().matches("^[a-zA-Z]+$")){
                    jTextBuscar1.setForeground(Color.red);
                } else{
                    jTextBuscar1.setForeground(Color.black);
                }
                if(!jTextBuscar2.getText().matches("^[a-zA-Z]+$")){
                    jTextBuscar2.setForeground(Color.red);
                } else{
                    jTextBuscar2.setForeground(Color.black);
                }
            }
        }
        if(jRadioButtonDocumento.isSelected()){
            if(jTextBuscar1.getText().matches("^[0-9]+$")){
                valido = true;
                jTextBuscar1.setForeground(Color.black);
            } else{
                jTextBuscar1.setForeground(Color.red);
            }
        }
        if(valido){
            ActionListener[] Coincidencias = jComboCoincidencias.getActionListeners();
            jComboCoincidencias.removeActionListener(Coincidencias[0]);
            jComboCoincidencias.removeAllItems();
            while(!coincidencias.esVacia()){
                coincidencias.sacarPersonaDePila();
            }
            arrayPersonas=null;
            if(jRadioButtonDocumento.isSelected()){
                Bienvenido.personas.buscarPorCI(jComboTCI.getSelectedItem().toString()+jTextBuscar1.getText());
            } else{
                Bienvenido.personas.buscarPorNombre(jTextBuscar1.getText() + " " + jTextBuscar2.getText());
            }
            
            jPanelCoincidencia.setVisible(true);
            if(!coincidencias.esVacia()){
                Persona[] arrayP = new Persona[coincidencias.getTamanio()];
                arrayPersonas = arrayP;
                for(int i=0; i<arrayP.length; i++){
                    arrayP[i] = coincidencias.sacarPersonaDePila();
                    if(arrayP[i].getMEntrada()<10){
                        jComboCoincidencias.addItem(arrayP[i].getDEntrada() + " " + arrayP[i].getHEntrada() + ":0" + arrayP[i].getMEntrada());
                    } else{
                        jComboCoincidencias.addItem(arrayP[i].getDEntrada() + " " + arrayP[i].getHEntrada() + ":" + arrayP[i].getMEntrada());
                    }
                }
                jLabelCoincidencia.setText("Se consiguieron coincidencias en las siguientes fechas:");
                jComboCoincidencias.setEnabled(true);
                jComboCoincidencias.setVisible(true);
            } else{
                jLabelCoincidencia.setText("No se consiguieron coincidencias.");
                jPanelOcupado.setVisible(false);
                jLabelDocumento.setVisible(false);
                jComboCoincidencias.setEnabled(false);
                jComboCoincidencias.setVisible(false);
                jLabelDia.setVisible(false);
                jComboDia.setVisible(false);
                jComboDia.setEnabled(false);
                jLabelHEntrada1.setVisible(false);
                jLabelHEntrada2.setVisible(false);
                jComboHEntrada.setVisible(false);
                jComboHEntrada.setEnabled(false);
                jComboMEntrada.setVisible(false);
                jComboMEntrada.setEnabled(false);
                jLabelNombre.setVisible(false);
                jLabelApellido.setVisible(false);
                jTextFieldNombre.setVisible(false);
                jTextFieldNombre.setEnabled(false);
                jTextFieldApellido.setVisible(false);
                jTextFieldApellido.setEnabled(false);
                jComboBoxTCI.setVisible(false);
                jComboBoxTCI.setEnabled(false);
                jTextFieldCI.setVisible(false);
                jTextFieldCI.setEnabled(false);
                jLabelHSalida1.setVisible(false);
                jLabelHSalida2.setVisible(false);
                jComboHSalida.setVisible(false);
                jComboHSalida.setEnabled(false);
                jComboMSalida.setVisible(false);
                jComboMSalida.setEnabled(false);
                jLabel1.setVisible(false);
                jLabel3.setVisible(false);
                jLabel6.setVisible(false);
                jCheckBoxVehiculo.setVisible(false);
                jComboBoxTCI.setEnabled(false);
                jLabelTVehiculo1.setVisible(false);
                jLabelTVehiculo2.setVisible(false);
                jComboTVehiculo.setVisible(false);
                jComboTVehiculo.setEnabled(false);
                jLabelMarca.setVisible(false);
                jComboMarca.setVisible(false);
                jComboMarca.setEnabled(false);
                jLabelColor.setVisible(false);
                jComboColor.setVisible(false);
                jComboColor.setEnabled(false);
                jLabelPlaca.setVisible(false);
                jTextFieldPlaca.setVisible(false);
                jTextFieldPlaca.setEnabled(false);
                jLabelPuesto.setVisible(false);
                jComboSector.setVisible(false);
                jComboSector.setEnabled(false);
                jComboNPuesto.setVisible(false);
                jComboNPuesto.setEnabled(false);
                jComboCoincidencias.removeAllItems();
                jComboCoincidencias.setVisible(false);
                jComboCoincidencias.setEnabled(false);
                jComboCompra.setVisible(false);
                jComboTiendas.setVisible(false);
                jComboProductos.setVisible(false);
                jLabelTotal.setVisible(false);
                jTextUnidades.setVisible(false);
                jRadioButtonOnline.setVisible(false);
                jRadioButtonPresencial.setVisible(false);
                jLabelPrecio.setVisible(false);
                jComboMetodoPago.setVisible(false);
                jLabelNCompra.setVisible(false);
                jLabelTienda.setVisible(false);
                jLabelProducto.setVisible(false);
                jLabelMPago.setVisible(false);
                jLabelUnidades.setVisible(false);
                jLabelTCompra.setVisible(false);
            }
            jComboCoincidencias.addActionListener(Coincidencias[0]);
        }
        
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jComboCoincidenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCoincidenciasActionPerformed
        if(jComboCoincidencias.getSelectedItem()!=null && jComboCoincidencias.isEnabled()){
            jPanelOcupado.setVisible(false);
            jComboDia.setEnabled(false);
            jComboHEntrada.setEnabled(false);
            jComboMEntrada.setEnabled(false);
            jComboHSalida.setEnabled(false);
            jComboMSalida.setEnabled(false);
            p = arrayPersonas[jComboCoincidencias.getSelectedIndex()];
            jLabelDia.setVisible(true);
            jComboDia.setVisible(true);
            jComboDia.setEnabled(true);
            jComboDia.setSelectedItem(p.getDEntrada());
            jLabelHEntrada1.setVisible(true);
            jLabelHEntrada2.setVisible(true);
            jComboHEntrada.setVisible(true);
            jComboHEntrada.setEnabled(true);
            ActionListener[] mEntrada = jComboMEntrada.getActionListeners();
            jComboMEntrada.removeActionListener(mEntrada[0]);
            jComboMEntrada.removeAllItems();
            for(int i=0; i<60;i++){
                if (i<10){
                    jComboMEntrada.addItem("0"+i);
                } else{
                    jComboMEntrada.addItem(String.valueOf(i));
                }
            }
            jComboMEntrada.addActionListener(mEntrada[0]);
            jComboMEntrada.setVisible(true);
            if(p.getMEntrada()<10){
                jComboMEntrada.setSelectedItem("0"+p.getMEntrada());
            } else{
                jComboMEntrada.setSelectedItem(String.valueOf(p.getMEntrada()));
            }
            jLabel1.setVisible(true);
            jLabel3.setVisible(true);
            jLabelDocumento.setVisible(true);
            jComboMEntrada.setEnabled(true);
            jLabelNombre.setVisible(true);
            jLabelApellido.setVisible(true);
            jTextFieldNombre.setVisible(true);
            jTextFieldNombre.setEnabled(true);
            jTextFieldNombre.setText(p.getNombre());
            jTextFieldApellido.setVisible(true);
            jTextFieldApellido.setEnabled(true);
            jTextFieldApellido.setText(p.getApellido());
            jComboBoxTCI.setVisible(true);
            jComboBoxTCI.setEnabled(true);
            jComboBoxTCI.setSelectedItem(p.getTci());
            jTextFieldCI.setVisible(true);
            jTextFieldCI.setEnabled(true);
            jTextFieldCI.setText(p.getCi());
            jLabelHSalida1.setVisible(true);
            jLabelHSalida2.setVisible(true);
            jComboHSalida.setVisible(true);
            jComboHSalida.setEnabled(true);
            jComboMSalida.setVisible(true);
            jComboMSalida.setEnabled(true);
            jCheckBoxVehiculo.setVisible(true);
            jCheckBoxVehiculo.setEnabled(true);
            jButtonEliminar.setVisible(true);
            jButtonEliminar.setEnabled(true);
            jButtonConfirmarC.setVisible(true);
            jButtonConfirmarC.setEnabled(true);
            if(p.getCarro()!=null){
                jLabel6.setVisible(true);
                jCheckBoxVehiculo.setSelected(true);
                puesto = encontrarPuesto(p);
                jLabelTVehiculo1.setVisible(true);
                jLabelTVehiculo2.setVisible(true);
                jComboTVehiculo.setVisible(true);
                jComboTVehiculo.setEnabled(true);
                jComboTVehiculo.setSelectedItem(p.getCarro().getTipo());
                jLabelMarca.setVisible(true);
                jComboMarca.setVisible(true);
                jComboMarca.setEnabled(true);
                jComboMarca.setSelectedItem(p.getCarro().getMarca());
                jLabelColor.setVisible(true);
                jComboColor.setVisible(true);
                jComboColor.setEnabled(true);
                jComboColor.setSelectedItem(p.getCarro().getColor());
                jLabelPlaca.setVisible(true);
                jTextFieldPlaca.setVisible(true);
                jTextFieldPlaca.setEnabled(true);
                jTextFieldPlaca.setText(p.getCarro().getPlaca());
                jLabelPuesto.setVisible(true);
                jComboSector.setVisible(true);
                jComboSector.setEnabled(true);
                jComboNPuesto.setVisible(true);
                jComboNPuesto.setEnabled(true);
                if(puesto!=null){
                    jComboSector.setSelectedItem(puesto.getSector());
                }
                jComboNPuesto.removeAllItems();
                if(jComboSector.getSelectedIndex()==0 || jComboSector.getSelectedIndex()==6){
                    for(int i=0; i<100; i++){
                        jComboNPuesto.addItem(Integer.toString(i+1));
                    }
                }else{
                    for(int i=0; i<500; i++){
                        jComboNPuesto.addItem(Integer.toString(i+1));
                    }
                }
                if(puesto!=null){
                    jComboNPuesto.setSelectedItem(Integer.toString(puesto.getNumero()));
                }
            } else{
                jCheckBoxVehiculo.setSelected(false);
                jLabel6.setVisible(false);
                jLabelTVehiculo1.setVisible(false);
                jLabelTVehiculo2.setVisible(false);
                jComboTVehiculo.setVisible(false);
                jComboTVehiculo.setEnabled(false);
                jLabelMarca.setVisible(false);
                jComboMarca.setVisible(false);
                jComboMarca.setEnabled(false);
                jLabelColor.setVisible(false);
                jComboColor.setVisible(false);
                jComboColor.setEnabled(false);
                jLabelPlaca.setVisible(false);
                jTextFieldPlaca.setVisible(false);
                jTextFieldPlaca.setEnabled(false);
                jLabelPuesto.setVisible(false);
                jComboSector.setVisible(false);
                jComboSector.setEnabled(false);
                jComboNPuesto.setVisible(false);
                jComboNPuesto.setEnabled(false);
            }
            if(!p.getCompras().esVacia()){
                jComboMetodoPago.setEnabled(false);
                jComboCompra.setVisible(true);
                jComboCompra.setEnabled(true);
                jComboProductos.setVisible(true);
                jComboProductos.setEnabled(true);
                jComboTiendas.setVisible(true);
                jComboTiendas.setEnabled(true);
                ActionListener[] compra = jComboCompra.getActionListeners();
                jComboCompra.removeActionListener(compra[0]);
                jComboCompra.removeAllItems();
                jComboCompra.addActionListener(compra[0]);
                compras = p.getCompras().getArrayCompras();
                for(int i=0; i<compras.length; i++){
                    jComboCompra.addItem(1+i);
                }
                jLabelTotal.setVisible(true);
                jTextUnidades.setVisible(true);
                jRadioButtonOnline.setVisible(true);
                jRadioButtonOnline.setEnabled(true);
                jRadioButtonPresencial.setVisible(true);
                jRadioButtonPresencial.setEnabled(true);
                jTextUnidades.setEnabled(true);
                jTextUnidades.setVisible(true);
                jComboMetodoPago.setVisible(true);
                jComboMetodoPago.setEnabled(true);
                jLabelPrecio.setVisible(true);
                jLabelNCompra.setVisible(true);
                jLabelTienda.setVisible(true);
                jLabelProducto.setVisible(true);
                jLabelMPago.setVisible(true);
                jLabelUnidades.setVisible(true);
                jLabelTCompra.setVisible(true);
            }
        }
    }//GEN-LAST:event_jComboCoincidenciasActionPerformed

    private void jRadioButtonNombreApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNombreApellidoActionPerformed
        if(jRadioButtonNombreApellido.isSelected()){
            jLabelDia.setVisible(false);
            jComboDia.setVisible(false);
            jComboDia.setEnabled(false);
            jLabelDocumento.setVisible(false);
            jLabelHEntrada1.setVisible(false);
            jLabelHEntrada2.setVisible(false);
            jComboHEntrada.setVisible(false);
            jComboHEntrada.setEnabled(false);
            jComboMEntrada.setVisible(false);
            jComboMEntrada.setEnabled(false);
            jLabelNombre.setVisible(false);
            jLabelApellido.setVisible(false);
            jTextFieldNombre.setVisible(false);
            jTextFieldNombre.setEnabled(false);
            jTextFieldApellido.setVisible(false);
            jTextFieldApellido.setEnabled(false);
            jComboBoxTCI.setVisible(false);
            jComboBoxTCI.setEnabled(false);
            jTextFieldCI.setVisible(false);
            jTextFieldCI.setEnabled(false);
            jLabelHSalida1.setVisible(false);
            jLabelHSalida2.setVisible(false);
            jComboHSalida.setVisible(false);
            jComboHSalida.setEnabled(false);
            jComboMSalida.setVisible(false);
            jComboMSalida.setEnabled(false);
            jCheckBoxVehiculo.setVisible(false);
            jComboBoxTCI.setEnabled(false);
            jLabelTVehiculo1.setVisible(false);
            jLabelTVehiculo2.setVisible(false);
            jComboTVehiculo.setVisible(false);
            jComboTVehiculo.setEnabled(false);
            jLabelMarca.setVisible(false);
            jComboMarca.setVisible(false);
            jComboMarca.setEnabled(false);
            jLabelColor.setVisible(false);
            jComboColor.setVisible(false);
            jComboColor.setEnabled(false);
            jLabelPlaca.setVisible(false);
            jTextFieldPlaca.setVisible(false);
            jTextFieldPlaca.setEnabled(false);
            jLabelPuesto.setVisible(false);
            jComboSector.setVisible(false);
            jComboSector.setEnabled(false);
            jComboNPuesto.setVisible(false);
            jComboNPuesto.setEnabled(false);
            jPanelCoincidencia.setVisible(false);
            jComboCoincidencias.removeAllItems();
            jComboCoincidencias.setVisible(false);
            jComboCoincidencias.setEnabled(false);
            jTextBuscar1.setText("");
            jLabelBNombre.setVisible(true);
            jLabelBNombre.setVisible(true);
            jLabelBApellido.setVisible(true);
            jTextBuscar2.setVisible(true);
            jTextBuscar2.setEnabled(true);
            jTextBuscar2.setText("");
            jComboTCI.setVisible(false);
            jComboTCI.setEnabled(false);
            jButtonBuscar.setBounds(800, jButtonBuscar.getY(), jButtonBuscar.getWidth(), jButtonBuscar.getHeight());
            jComboCompra.setVisible(false);
            jComboTiendas.setVisible(false);
            jComboProductos.setVisible(false);
            jLabelTotal.setVisible(false);
            jTextUnidades.setVisible(false);
            jRadioButtonOnline.setVisible(false);
            jRadioButtonPresencial.setVisible(false);
            jLabelPrecio.setVisible(false);
            jComboMetodoPago.setVisible(false);
            jLabelNCompra.setVisible(false);
            jLabelTienda.setVisible(false);
            jLabelProducto.setVisible(false);
            jLabelMPago.setVisible(false);
            jLabelUnidades.setVisible(false);
            jLabelTCompra.setVisible(false);
            jLabel1.setVisible(false);
            jLabel3.setVisible(false);
            jLabel6.setVisible(false);
            jPanelOcupado.setVisible(false);
            jButtonEliminar.setVisible(false);
            jButtonEliminar.setEnabled(false);
            jButtonConfirmarC.setVisible(false);
            jButtonConfirmarC.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioButtonNombreApellidoActionPerformed

    private void jRadioButtonDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDocumentoActionPerformed
        if(jRadioButtonDocumento.isSelected()){
            jLabelDia.setVisible(false);
            jComboDia.setVisible(false);
            jComboDia.setEnabled(false);
            jLabelDocumento.setVisible(false);
            jLabelHEntrada1.setVisible(false);
            jLabelHEntrada2.setVisible(false);
            jComboHEntrada.setVisible(false);
            jComboHEntrada.setEnabled(false);
            jComboMEntrada.setVisible(false);
            jComboMEntrada.setEnabled(false);
            jLabelNombre.setVisible(false);
            jLabelApellido.setVisible(false);
            jTextFieldNombre.setVisible(false);
            jTextFieldNombre.setEnabled(false);
            jTextFieldApellido.setVisible(false);
            jTextFieldApellido.setEnabled(false);
            jComboBoxTCI.setVisible(false);
            jComboBoxTCI.setEnabled(false);
            jTextFieldCI.setVisible(false);
            jTextFieldCI.setEnabled(false);
            jLabelHSalida1.setVisible(false);
            jLabelHSalida2.setVisible(false);
            jComboHSalida.setVisible(false);
            jComboHSalida.setEnabled(false);
            jComboMSalida.setVisible(false);
            jComboMSalida.setEnabled(false);
            jCheckBoxVehiculo.setVisible(false);
            jComboBoxTCI.setEnabled(false);
            jLabelTVehiculo1.setVisible(false);
            jLabelTVehiculo2.setVisible(false);
            jComboTVehiculo.setVisible(false);
            jComboTVehiculo.setEnabled(false);
            jLabelMarca.setVisible(false);
            jComboMarca.setVisible(false);
            jComboMarca.setEnabled(false);
            jLabelColor.setVisible(false);
            jComboColor.setVisible(false);
            jComboColor.setEnabled(false);
            jLabelPlaca.setVisible(false);
            jTextFieldPlaca.setVisible(false);
            jTextFieldPlaca.setEnabled(false);
            jLabelPuesto.setVisible(false);
            jComboSector.setVisible(false);
            jComboSector.setEnabled(false);
            jComboNPuesto.setVisible(false);
            jComboNPuesto.setEnabled(false);
            jPanelCoincidencia.setVisible(false);
            jComboCoincidencias.removeAllItems();
            jComboCoincidencias.setVisible(false);
            jComboCoincidencias.setEnabled(false);
            jLabelBNombre.setVisible(false);
            jTextBuscar2.setVisible(false);
            jTextBuscar2.setEnabled(false);
            jTextBuscar2.setText("");
            jTextBuscar1.setText("");
            jLabelBApellido.setVisible(false);
            jComboTCI.setEnabled(true);
            jComboTCI.setVisible(true);
            jButtonBuscar.setBounds(560, jButtonBuscar.getY(), jButtonBuscar.getWidth(), jButtonBuscar.getHeight());
            jComboCompra.setVisible(false);
            jComboTiendas.setVisible(false);
            jComboProductos.setVisible(false);
            jLabelTotal.setVisible(false);
            jTextUnidades.setVisible(false);
            jRadioButtonOnline.setVisible(false);
            jRadioButtonPresencial.setVisible(false);
            jLabelPrecio.setVisible(false);
            jComboMetodoPago.setVisible(false);
            jLabelNCompra.setVisible(false);
            jLabelTienda.setVisible(false);
            jLabelProducto.setVisible(false);
            jLabelMPago.setVisible(false);
            jLabelUnidades.setVisible(false);
            jLabelTCompra.setVisible(false);
            jLabel1.setVisible(false);
            jLabel3.setVisible(false);
            jLabel6.setVisible(false);
            jPanelOcupado.setVisible(false);
            jButtonEliminar.setVisible(false);
            jButtonEliminar.setEnabled(false);
            jButtonConfirmarC.setVisible(false);
            jButtonConfirmarC.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioButtonDocumentoActionPerformed

    private void jCheckBoxVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxVehiculoActionPerformed
        if(jCheckBoxVehiculo.isSelected()){
            jLabel6.setVisible(true);
            jLabelTVehiculo1.setVisible(true);
            jLabelTVehiculo2.setVisible(true);
            jComboTVehiculo.setVisible(true);
            jComboTVehiculo.setEnabled(true);
            jLabelMarca.setVisible(true);
            jComboMarca.setVisible(true);
            jComboMarca.setEnabled(true);
            jLabelColor.setVisible(true);
            jComboColor.setVisible(true);
            jComboColor.setEnabled(true);
            jLabelPlaca.setVisible(true);
            jTextFieldPlaca.setVisible(true);
            jTextFieldPlaca.setEnabled(true);
            jLabelPuesto.setVisible(true);
            jComboSector.setVisible(true);
            jComboSector.setEnabled(true);
            jComboNPuesto.setVisible(true);
            jComboNPuesto.setEnabled(true);
            if(puesto!=null){
                jComboSector.setSelectedItem(puesto.getSector());
                jComboNPuesto.removeAllItems();
                if(jComboSector.getSelectedIndex()==0 || jComboSector.getSelectedIndex()==6){
                    for(int i=0; i<100; i++){
                        jComboNPuesto.addItem(Integer.toString(i+1));
                    }
                }else{
                    for(int i=0; i<500; i++){
                        jComboNPuesto.addItem(Integer.toString(i+1));
                    }
                }
                jComboNPuesto.setSelectedItem(Integer.toString(puesto.getNumero()));
            }
        } else{
            jLabel6.setVisible(false);
            jLabelTVehiculo1.setVisible(false);
            jLabelTVehiculo2.setVisible(false);
            jComboTVehiculo.setVisible(false);
            jLabelMarca.setVisible(false);
            jComboMarca.setVisible(false);
            jLabelColor.setVisible(false);
            jComboColor.setVisible(false);
            jLabelPlaca.setVisible(false);
            jTextFieldPlaca.setVisible(false);
            jLabelPuesto.setVisible(false);
            jComboSector.setVisible(false);
            jComboNPuesto.setVisible(false);
            jPanelOcupado.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBoxVehiculoActionPerformed

    private void jComboSectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboSectorActionPerformed
        jComboNPuesto.removeAllItems();
        if(jComboSector.getSelectedIndex()==0 || jComboSector.getSelectedIndex()==6){
            for(int i=0; i<100; i++){
                jComboNPuesto.addItem(Integer.toString(i+1));
            }
        }else{
            for(int i=0; i<500; i++){
                jComboNPuesto.addItem(Integer.toString(i+1));
            }
        }
    }//GEN-LAST:event_jComboSectorActionPerformed

    private void jComboHEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboHEntradaActionPerformed
        ActionListener[] hSalida = jComboHSalida.getActionListeners();
        jComboHSalida.removeActionListener(hSalida[0]);
        jComboHSalida.removeAllItems();
        int d;
        if(jComboDia.getSelectedItem().equals("Domingo")){
            d = 21;
        } else{
            d = 22;
        }
        for(int i=Integer.parseInt(jComboHEntrada.getSelectedItem().toString()); i<d; i++){
            jComboHSalida.addItem(String.valueOf(i));
        }
        jComboHSalida.addActionListener(hSalida[0]);
        if(!jComboHSalida.isEnabled()){
            jComboHSalida.setSelectedItem(String.valueOf(p.getHSalida()));
        } else if(jComboHEntrada.getSelectedItem().equals(jComboHSalida.getSelectedItem())){
            jComboMSalida.removeAllItems();
            for(int i=Integer.parseInt(jComboMEntrada.getSelectedItem().toString()); i<60; i++){
                if(i<10){
                    jComboMSalida.addItem("0"+i);
                } else{
                    jComboMSalida.addItem(String.valueOf(i));
                }
            }
        }
    }//GEN-LAST:event_jComboHEntradaActionPerformed

    private void jComboDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboDiaActionPerformed
        ActionListener[] hEntrada = jComboHEntrada.getActionListeners();
        jComboHEntrada.removeActionListener(hEntrada[0]);
        jComboHEntrada.removeAllItems();
        if(jComboDia.getSelectedItem().equals("Domingo")){
            for(int i=12; i<20;i++){
                jComboHEntrada.addItem(String.valueOf(i));
            }
        } else{
            for(int i=11; i<21;i++){
                jComboHEntrada.addItem(String.valueOf(i));
            }
        }
        jComboHEntrada.addActionListener(hEntrada[0]);
        if(!jComboHEntrada.isEnabled()){
            jComboHEntrada.setSelectedItem(String.valueOf(p.getHEntrada()));
        } else{
            ActionListener[] mEntrada = jComboMEntrada.getActionListeners();
            jComboMEntrada.removeActionListener(mEntrada[0]);
            jComboMEntrada.removeAllItems();
            for(int i=0; i<60; i++){
                if(i<10){
                    jComboMEntrada.addItem("0"+i);
                } else{
                    jComboMEntrada.addItem(String.valueOf(i));
                }
            }
            jComboMEntrada.addActionListener(mEntrada[0]);
            ActionListener[] hSalida = jComboHSalida.getActionListeners();
            jComboHSalida.removeActionListener(hSalida[0]);
            jComboHSalida.removeAllItems();
            int h;
            if(jComboDia.getSelectedItem().equals("Domingo")){
                h = 21;
            } else{
                h = 22;
            }
            for(int i=Integer.parseInt(jComboHEntrada.getSelectedItem().toString()); i<h; i++){
                jComboHSalida.addItem(String.valueOf(i));
            }
            jComboHSalida.addActionListener(hSalida[0]);
            jComboMSalida.removeAllItems();
            for(int i=0; i<60; i++){
                if(i<10){
                    jComboMSalida.addItem("0"+i);
                }else{
                    jComboMSalida.addItem(String.valueOf(i));
                }
            }
        }
    }//GEN-LAST:event_jComboDiaActionPerformed

    private void jComboMEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboMEntradaActionPerformed
        jComboMSalida.removeAllItems();
        int m;    
        if(jComboHEntrada.getSelectedItem().equals(jComboHSalida.getSelectedItem())){
                m = Integer.parseInt(jComboMEntrada.getSelectedItem().toString());
            }else{
                m=0;
            }
            for(int i=m; i<60; i++){
                if(i<10){
                    jComboMSalida.addItem("0"+i);
                } else{
                    jComboMSalida.addItem(String.valueOf(i));
                }
            }
        if(!jComboMSalida.isEnabled()){
            if(p.getMSalida()<10){
                jComboMSalida.setSelectedItem(String.valueOf("0"+p.getMSalida()));
            } else{
                jComboMSalida.setSelectedItem(String.valueOf(String.valueOf(p.getMSalida())));
            }
        }
    }//GEN-LAST:event_jComboMEntradaActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        try {
            Bienvenido B = new Bienvenido();
            B.setVisible(true);
            dispose();
        } catch (IOException ex) {
            Logger.getLogger(menuEditar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jComboCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCompraActionPerformed
        jComboTiendas.setSelectedItem(compras[jComboCompra.getSelectedIndex()].getTienda().getNombre());
        jTextUnidades.setText(String.valueOf(compras[jComboCompra.getSelectedIndex()].getUnidades()));
        jComboMetodoPago.removeAllItems();
        if(compras[jComboCompra.getSelectedIndex()].getTipoCompra().equals("Online")){
            jRadioButtonOnline.setSelected(true);
            jComboMetodoPago.addItem("Zelle");
            jComboMetodoPago.addItem("PagoMovil");
            jComboMetodoPago.addItem("Transferencia");
        } else{
            jRadioButtonPresencial.setSelected(true);
            jComboMetodoPago.addItem("Efectivo");
            jComboMetodoPago.addItem("TDC");
            jComboMetodoPago.addItem("TDD");
        }
        jComboMetodoPago.setSelectedItem(compras[jComboCompra.getSelectedIndex()].getMetodoPago());
        jLabelPrecio.setText("Precio: " + compras[jComboCompra.getSelectedIndex()].getProducto().getPrecio() + "$");
        jLabelTotal.setText("Total: " + compras[jComboCompra.getSelectedIndex()].getPrecioTotal() + "$");
    }//GEN-LAST:event_jComboCompraActionPerformed

    private void jComboTiendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTiendasActionPerformed
        ActionListener[] prod = jComboProductos.getActionListeners();
        jComboProductos.removeActionListener(prod[0]);
        jComboProductos.removeAllItems();
        productos = Bienvenido.tiendas.buscarTienda(jComboTiendas.getSelectedIndex()+1).getProductos().getArrayProductos();
        for(int i=0; i<productos.length; i++){
            jComboProductos.addItem(productos[i].getNombre());
        }
        jComboProductos.addActionListener(prod[0]);
        jComboProductos.setSelectedItem(compras[jComboCompra.getSelectedIndex()].getProducto().getNombre());
        if (jComboProductos.isEnabled()){
            jComboProductos.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jComboTiendasActionPerformed

    private void jRadioButtonOnlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonOnlineActionPerformed
        jComboMetodoPago.removeAllItems();
        if(jRadioButtonOnline.isSelected()){
            jComboMetodoPago.addItem("Zelle");
            jComboMetodoPago.addItem("PagoMovil");
            jComboMetodoPago.addItem("Transferencia");
        }
    }//GEN-LAST:event_jRadioButtonOnlineActionPerformed

    private void jRadioButtonPresencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPresencialActionPerformed
        jComboMetodoPago.removeAllItems();
        if(jRadioButtonPresencial.isSelected()){
            jComboMetodoPago.addItem("Efectivo");
            jComboMetodoPago.addItem("TDC");
            jComboMetodoPago.addItem("TDD");
        }
    }//GEN-LAST:event_jRadioButtonPresencialActionPerformed

    private void jComboProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboProductosActionPerformed
        jLabelPrecio.setText("Precio: " + Bienvenido.tiendas.buscarTienda(jComboTiendas.getSelectedIndex()+1).getProductos().buscarProducto(jComboProductos.getSelectedItem().toString()).getPrecio() + "$");
        if(jTextUnidades.isEnabled() && !jTextUnidades.getText().equals("")){
            jLabelTotal.setText("Total: " + Bienvenido.tiendas.buscarTienda(jComboTiendas.getSelectedIndex()+1).getProductos().buscarProducto(jComboProductos.getSelectedItem().toString()).getPrecio()*Integer.parseInt(jTextUnidades.getText()) + "$");
        }
    }//GEN-LAST:event_jComboProductosActionPerformed

    private void jTextUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUnidadesActionPerformed
        if(!jTextUnidades.getText().matches("^[1-9]+$")){
            jLabelTotal.setText("Total:");
            jTextUnidades.setForeground(Color.red);
        } else{
            jTextUnidades.setForeground(Color.black);
            jLabelTotal.setText("Total: " + Bienvenido.tiendas.buscarTienda(jComboTiendas.getSelectedIndex()+1).getProductos().buscarProducto(jComboProductos.getSelectedItem().toString()).getPrecio()*Integer.parseInt(jTextUnidades.getText()) + "$");
        }
    }//GEN-LAST:event_jTextUnidadesActionPerformed

    private void jButtonConfirmarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarCActionPerformed
        boolean Personavalido = false;
        boolean puestoValido = false;
        if(jTextFieldNombre.getText().matches("^[a-zA-Z]+$") && jTextFieldApellido.getText().matches("^[a-zA-Z]+$") && jTextFieldCI.getText().matches("^[0-9]+$")){
            Personavalido = true;
            jTextFieldNombre.setForeground(Color.black);
            jTextFieldNombre.setForeground(Color.black);
            jTextFieldCI.setForeground(Color.black);
            jTextUnidades.setForeground(Color.black);
            p.setNombre(jTextFieldNombre.getText());
            p.setApellido(jTextFieldApellido.getText());
            p.setTci(jComboBoxTCI.getSelectedItem().toString());
            p.setCi(jTextFieldCI.getText());
            p.setDEntrada(jComboDia.getSelectedItem().toString());
            p.setHEntrada(Integer.parseInt(jComboHEntrada.getSelectedItem().toString()));
            p.setMEntrada(Integer.parseInt(jComboMEntrada.getSelectedItem().toString()));
            p.setHSalida(Integer.parseInt(jComboHSalida.getSelectedItem().toString()));
            p.setMSalida(Integer.parseInt(jComboMSalida.getSelectedItem().toString()));
            if(!p.getCompras().esVacia()){
                if(!(jTextUnidades.getText().matches("^[0-9]+$") && Integer.parseInt(jTextUnidades.getText())!=0)){
                    Personavalido = false;
                    jTextUnidades.setForeground(Color.red);
                } else{
                    jTextUnidades.setForeground(Color.black);
                    Compra compraNueva = compras[jComboCompra.getSelectedIndex()];
                    p.getCompras().eliminarCompra(compraNueva);
                    compraNueva.setTienda(Bienvenido.tiendas.buscarTienda(jComboTiendas.getSelectedIndex()+1));
                    compraNueva.setProducto(compraNueva.getTienda().getProductos().buscarProducto(jComboProductos.getSelectedItem().toString()));
                    compraNueva.setUnidades(Integer.parseInt(jTextUnidades.getText()));
                    compraNueva.setPrecioTotal(Integer.parseInt(jTextUnidades.getText())*compraNueva.getProducto().getPrecio());
                    if(jRadioButtonOnline.isSelected()){
                        compraNueva.setTipoCompra("Online");
                    } else{
                        compraNueva.setTipoCompra("Presencial");
                    }
                    compraNueva.setMetodoPago(jComboMetodoPago.getSelectedItem().toString());
                    p.getCompras().agregarCompraAlFinal(compraNueva);
                }
            }
        } else{
            if(!jTextFieldNombre.getText().matches("^[a-zA-Z]+$")){
                jTextFieldNombre.setForeground(Color.red);
            } else{
                jTextFieldNombre.setForeground(Color.black);
            }
            if(!jTextFieldApellido.getText().matches("^[a-zA-Z]+$")){
                jTextFieldApellido.setForeground(Color.red);
            } else{
                jTextFieldApellido.setForeground(Color.black);
            }
            if(!jTextFieldCI.getText().matches("^[0-9]+$")){
                jTextFieldCI.setForeground(Color.red);
            } else{
                jTextFieldCI.setForeground(Color.black);
            }
            if(!jTextUnidades.getText().matches("^[0-9]+$") && Integer.parseInt(jTextUnidades.getText())==0){
                jTextUnidades.setForeground(Color.red);
            } else{
                jTextUnidades.setForeground(Color.black);
            }
        }
        if(Personavalido){
            puestoEst puestoNuevo = null;
            if(jCheckBoxVehiculo.isSelected()){
                if(jTextFieldPlaca.getText().matches("^[A-Z0-9]*$")){
                    jTextFieldPlaca.setForeground(Color.black);
                    p.setCarro(new Vehiculo(p, jComboTVehiculo.getSelectedItem().toString(), jTextFieldPlaca.getText(), jComboColor.getSelectedItem().toString(), jComboMarca.getSelectedItem().toString()));
                    puestoEst puestoCopia = puesto;
                    if(puesto!=null){
                        puesto.getOcupantes().eliminarPersona(p);
                    }
                    switch (jComboSector.getSelectedItem().toString()){
                        case "P":
                            puestoNuevo = Bienvenido.sectoresMotos[0][jComboNPuesto.getSelectedIndex()];
                            break;
                        case "M":
                            puestoNuevo = Bienvenido.sectoresCarros[0][jComboNPuesto.getSelectedIndex()];
                            break;
                        case "S":
                            puestoNuevo = Bienvenido.sectoresCarros[1][jComboNPuesto.getSelectedIndex()];
                            break;
                        case "R":
                            puestoNuevo = Bienvenido.sectoresCarros[2][jComboNPuesto.getSelectedIndex()];
                            break;
                        case "G":
                            puestoNuevo = Bienvenido.sectoresCarros[3][jComboNPuesto.getSelectedIndex()];
                            break;
                        case "B1":
                            puestoNuevo = Bienvenido.sectoresCarros[4][jComboNPuesto.getSelectedIndex()];
                            break;
                        case "B2":
                            puestoNuevo = Bienvenido.sectoresMotos[1][jComboNPuesto.getSelectedIndex()];
                            break;
                    }
                    if(puestoNuevo.getOcupantes().estaOcupado(p)){
                        puesto = puestoCopia;
                        jPanelOcupado.setVisible(true);
                    } else{
                        puestoNuevo.getOcupantes().agregarPersonaAlFinal(p);
                        jPanelOcupado.setVisible(false);
                        switch (jComboSector.getSelectedItem().toString()){
                            case "P":
                                Bienvenido.sectoresMotos[0][jComboNPuesto.getSelectedIndex()] = puestoNuevo;
                                break;
                            case "M":
                                Bienvenido.sectoresCarros[0][jComboNPuesto.getSelectedIndex()] = puestoNuevo;
                                break;
                            case "S":
                                Bienvenido.sectoresCarros[1][jComboNPuesto.getSelectedIndex()] = puestoNuevo;
                                break;
                            case "R":
                                Bienvenido.sectoresCarros[2][jComboNPuesto.getSelectedIndex()] = puestoNuevo;
                                break;
                            case "G":
                                Bienvenido.sectoresCarros[3][jComboNPuesto.getSelectedIndex()] = puestoNuevo;
                                break;
                            case "B1":
                                Bienvenido.sectoresCarros[4][jComboNPuesto.getSelectedIndex()] = puestoNuevo;
                                break;
                            case "B2":
                                Bienvenido.sectoresMotos[1][jComboNPuesto.getSelectedIndex()] = puestoNuevo;
                                break;
                        }
                        puestoValido = true;
                    }
                } else{
                   jTextFieldPlaca.setForeground(Color.red);
                }
            } else{
                p.setCarro(null);
                puestoValido = true;
            }
        }
        if(Personavalido && puestoValido){
            Bienvenido.personas.eliminarPersona(p);
            Bienvenido.personas.insertarPersona(p);
            try {
                Bienvenido B = new Bienvenido();
                B.setVisible(true);
                dispose();
            } catch (IOException ex) {
                Logger.getLogger(menuEditar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonConfirmarCActionPerformed

    private void jComboTVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTVehiculoActionPerformed
        jComboSector.removeAllItems();
        if(jComboTVehiculo.getSelectedItem().equals("Moto")){
            jComboSector.addItem("P");
            jComboSector.addItem("B2");
        } else{
            jComboSector.addItem("M");
            jComboSector.addItem("S");
            jComboSector.addItem("R");
            jComboSector.addItem("G");
            jComboSector.addItem("B1");
        }
    }//GEN-LAST:event_jComboTVehiculoActionPerformed

    private void jComboHSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboHSalidaActionPerformed
        if((jComboDia.getSelectedItem().equals("Domingo") && jComboHSalida.getSelectedItem().equals("20")) || (!jComboDia.getSelectedItem().equals("Domingo") && jComboHSalida.getSelectedItem().equals("21"))){
            jComboMSalida.removeAllItems();
            jComboMSalida.addItem("00");
        }
    }//GEN-LAST:event_jComboHSalidaActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        if(p!=null){
            Bienvenido.personas.eliminarPersona(p);
            if(puesto!=null){
                puesto.getOcupantes().eliminarPersona(p);
            }
            jPanelBorrar.setVisible(true);
            new Thread(){
                public void run(){
                    try{
                        Thread.sleep(3000);
                        jPanelBorrar.setVisible(false);
                        try {
                            Bienvenido B = new Bienvenido();
                            B.setVisible(true);
                            dispose();
                        } catch (IOException ex) {
                            Logger.getLogger(menuEditar.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }catch(Exception q){}
                }
            }.start();
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jComboMetodoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboMetodoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboMetodoPagoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuEditar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonConfirmarC;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JCheckBox jCheckBoxVehiculo;
    private javax.swing.JComboBox<String> jComboBoxTCI;
    private javax.swing.JComboBox<String> jComboCoincidencias;
    private javax.swing.JComboBox<String> jComboColor;
    private javax.swing.JComboBox<Integer> jComboCompra;
    private javax.swing.JComboBox<String> jComboDia;
    private javax.swing.JComboBox<String> jComboHEntrada;
    private javax.swing.JComboBox<String> jComboHSalida;
    private javax.swing.JComboBox<String> jComboMEntrada;
    private javax.swing.JComboBox<String> jComboMSalida;
    private javax.swing.JComboBox<String> jComboMarca;
    private javax.swing.JComboBox<String> jComboMetodoPago;
    private javax.swing.JComboBox<String> jComboNPuesto;
    private javax.swing.JComboBox<String> jComboProductos;
    private javax.swing.JComboBox<String> jComboSector;
    private javax.swing.JComboBox<String> jComboTCI;
    private javax.swing.JComboBox<String> jComboTVehiculo;
    private javax.swing.JComboBox<String> jComboTiendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelBApellido;
    private javax.swing.JLabel jLabelBNombre;
    private javax.swing.JLabel jLabelCoincidencia;
    private javax.swing.JLabel jLabelColor;
    private javax.swing.JLabel jLabelDia;
    private javax.swing.JLabel jLabelDocumento;
    private javax.swing.JLabel jLabelHEntrada1;
    private javax.swing.JLabel jLabelHEntrada2;
    private javax.swing.JLabel jLabelHSalida1;
    private javax.swing.JLabel jLabelHSalida2;
    private javax.swing.JLabel jLabelMPago;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelNCompra;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelProducto;
    private javax.swing.JLabel jLabelPuesto;
    private javax.swing.JLabel jLabelTCompra;
    private javax.swing.JLabel jLabelTVehiculo1;
    private javax.swing.JLabel jLabelTVehiculo2;
    private javax.swing.JLabel jLabelTienda;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelUnidades;
    private javax.swing.JPanel jPanelBorrar;
    private javax.swing.JPanel jPanelCoincidencia;
    private javax.swing.JPanel jPanelOcupado;
    private javax.swing.JRadioButton jRadioButtonDocumento;
    private javax.swing.JRadioButton jRadioButtonNombreApellido;
    private javax.swing.JRadioButton jRadioButtonOnline;
    private javax.swing.JRadioButton jRadioButtonPresencial;
    private javax.swing.JTextField jTextBuscar1;
    private javax.swing.JTextField jTextBuscar2;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldCI;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPlaca;
    private javax.swing.JTextField jTextUnidades;
    private javax.swing.JLabel pOcupado;
    // End of variables declaration//GEN-END:variables
}
