package Main;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class vEstacionamiento extends javax.swing.JFrame {

    Persona personaActual = DatosUsuario.usuariosEnSesion.verTope();
    boolean esMoto = DatosUsuario.usuariosEnSesion.verTope().getCarro().getTipo().equals("Moto");
    public vEstacionamiento() {
        initComponents();
        setVisible(true);
        setSize(1670, 675); //Tamano de la ventana.
        setLocationRelativeTo(null); //Para que la ventana se ubique en el centro de la pantalla.
        jLabelCBambu1.setVisible(false);
        jLabelCBambu2.setVisible(false);
        jLabelCGuayacan.setVisible(false);
        jLabelCMangle.setVisible(false);
        jLabelCPalma.setVisible(false);
        jLabelCRoble.setVisible(false);
        jLabelCSaman.setVisible(false);
        jPanelPValido.setVisible(false);
        jLabelPValido1.setVisible(false);
        jLabelPValido2.setVisible(false);
        jPanelOcupado.setVisible(false);
        jLabelOcupado1.setVisible(false);
        jLabelOcupado2.setVisible(false);
        if (esMoto){
            jLabelMangle.setVisible(false);
            jLabelSaman.setVisible(false);
            jLabelRoble.setVisible(false);
            jLabelGuayacan.setVisible(false);
            jLabelBambu1.setVisible(false);
            for (int i=0; i<100; i++){
                jComboNPuesto.addItem(Integer.toString(i+1));
            }
            jComboSPuesto.addItem("Sector Palma");
            jComboSPuesto.addItem("Sector Bambú 2");
            jLabelPValido2.setText("(Entre 1 y 100)");
        } else{
            jLabelPalma.setVisible(false);
            jLabelBambu2.setVisible(false);
            for (int i=0; i<500; i++){
                jComboNPuesto.addItem(Integer.toString(i+1));
            }
            jComboSPuesto.addItem("Sector Mangle");
            jComboSPuesto.addItem("Sector Samán");
            jComboSPuesto.addItem("Sector Roble");
            jComboSPuesto.addItem("Sector Guayacán");
            jComboSPuesto.addItem("Sector Bambú 1");
            jLabelPValido2.setText("(Entre 1 y 500)");
        }
        jComboNPuesto.setSelectedIndex(0);
        jComboSPuesto.setSelectedIndex(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCPalma = new javax.swing.JLabel();
        jLabelPalma = new javax.swing.JLabel();
        jLabelCMangle = new javax.swing.JLabel();
        jLabelCSaman = new javax.swing.JLabel();
        jLabelSaman = new javax.swing.JLabel();
        jLabelCBambu1 = new javax.swing.JLabel();
        jLabelBambu1 = new javax.swing.JLabel();
        jLabelCRoble = new javax.swing.JLabel();
        jLabelCGuayacan = new javax.swing.JLabel();
        jLabelGuayacan = new javax.swing.JLabel();
        jLabelCBambu2 = new javax.swing.JLabel();
        jLabelRoble = new javax.swing.JLabel();
        jLabelBambu2 = new javax.swing.JLabel();
        jPanelOcupado = new javax.swing.JPanel();
        jLabelOcupado1 = new javax.swing.JLabel();
        jLabelOcupado2 = new javax.swing.JLabel();
        jPanelSPuesto = new javax.swing.JPanel();
        jLabelSPuesto = new javax.swing.JLabel();
        jComboSPuesto = new javax.swing.JComboBox<>();
        jPanelInstruccion = new javax.swing.JPanel();
        jLabelNPuestos1 = new javax.swing.JLabel();
        jLabelNPuestos2 = new javax.swing.JLabel();
        jLabelMangle = new javax.swing.JLabel();
        jPanelNPuesto = new javax.swing.JPanel();
        jLabelNPuesto = new javax.swing.JLabel();
        jComboNPuesto = new javax.swing.JComboBox<>();
        jPanelConfirmar = new javax.swing.JPanel();
        jLabelConfirmar = new javax.swing.JLabel();
        jButtonConfirmar = new javax.swing.JButton();
        jPanelPValido = new javax.swing.JPanel();
        jLabelPValido1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelPValido2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Seleccione su sector de estacionamiento");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelCPalma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cartelPalma.png"))); // NOI18N
        getContentPane().add(jLabelCPalma);
        jLabelCPalma.setBounds(100, 30, 164, 127);

        jLabelPalma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sectorPalma.png"))); // NOI18N
        jLabelPalma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelPalmaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelPalmaMouseExited(evt);
            }
        });
        getContentPane().add(jLabelPalma);
        jLabelPalma.setBounds(10, 100, 178, 172);

        jLabelCMangle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cartelMangle.png"))); // NOI18N
        getContentPane().add(jLabelCMangle);
        jLabelCMangle.setBounds(190, 220, 164, 126);

        jLabelCSaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cartelSaman.png"))); // NOI18N
        getContentPane().add(jLabelCSaman);
        jLabelCSaman.setBounds(420, 300, 164, 126);

        jLabelSaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sectorSaman.png"))); // NOI18N
        jLabelSaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelSamanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelSamanMouseExited(evt);
            }
        });
        getContentPane().add(jLabelSaman);
        jLabelSaman.setBounds(330, 370, 240, 208);

        jLabelCBambu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cartelBambu1.png"))); // NOI18N
        getContentPane().add(jLabelCBambu1);
        jLabelCBambu1.setBounds(1450, 230, 164, 126);

        jLabelBambu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sectorBambu1.png"))); // NOI18N
        jLabelBambu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBambu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBambu1MouseExited(evt);
            }
        });
        getContentPane().add(jLabelBambu1);
        jLabelBambu1.setBounds(1550, 190, 101, 408);

        jLabelCRoble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cartelRoble.png"))); // NOI18N
        getContentPane().add(jLabelCRoble);
        jLabelCRoble.setBounds(660, 370, 164, 126);

        jLabelCGuayacan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cartelGuayacan.png"))); // NOI18N
        getContentPane().add(jLabelCGuayacan);
        jLabelCGuayacan.setBounds(1250, 380, 164, 126);

        jLabelGuayacan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sectorGuayacan.png"))); // NOI18N
        jLabelGuayacan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelGuayacanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelGuayacanMouseExited(evt);
            }
        });
        getContentPane().add(jLabelGuayacan);
        jLabelGuayacan.setBounds(1140, 370, 407, 230);

        jLabelCBambu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cartelBambu2.png"))); // NOI18N
        getContentPane().add(jLabelCBambu2);
        jLabelCBambu2.setBounds(1350, 10, 164, 127);

        jLabelRoble.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sectorRoble.png"))); // NOI18N
        jLabelRoble.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelRobleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelRobleMouseExited(evt);
            }
        });
        getContentPane().add(jLabelRoble);
        jLabelRoble.setBounds(600, 370, 517, 226);

        jLabelBambu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sectorBambu2.png"))); // NOI18N
        jLabelBambu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelBambu2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelBambu2MouseExited(evt);
            }
        });
        getContentPane().add(jLabelBambu2);
        jLabelBambu2.setBounds(1490, 50, 119, 160);

        jPanelOcupado.setBackground(new java.awt.Color(204, 255, 255));
        jPanelOcupado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 102), 5, true));

        jLabelOcupado1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelOcupado1.setText("Puesto ocupado.");
        jPanelOcupado.add(jLabelOcupado1);

        jLabelOcupado2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelOcupado2.setText("Por favor, seleccione un puesto distinto.");
        jPanelOcupado.add(jLabelOcupado2);

        getContentPane().add(jPanelOcupado);
        jPanelOcupado.setBounds(560, 170, 570, 90);

        jPanelSPuesto.setBackground(new java.awt.Color(204, 255, 255));
        jPanelSPuesto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 102), 5, true));

        jLabelSPuesto.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelSPuesto.setText("Indique el sector del puesto:");
        jPanelSPuesto.add(jLabelSPuesto);

        jComboSPuesto.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboSPuesto.setForeground(new java.awt.Color(204, 255, 255));
        jComboSPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboSPuestoActionPerformed(evt);
            }
        });
        jPanelSPuesto.add(jComboSPuesto);

        getContentPane().add(jPanelSPuesto);
        jPanelSPuesto.setBounds(560, 170, 270, 80);

        jPanelInstruccion.setBackground(new java.awt.Color(204, 255, 255));
        jPanelInstruccion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 102), 5, true));

        jLabelNPuestos1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelNPuestos1.setText("Mueva el cursor sobre el sector");
        jPanelInstruccion.add(jLabelNPuestos1);

        jLabelNPuestos2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelNPuestos2.setText("para saber su nombre.");
        jPanelInstruccion.add(jLabelNPuestos2);

        getContentPane().add(jPanelInstruccion);
        jPanelInstruccion.setBounds(680, 70, 320, 70);

        jLabelMangle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sectorMangle.png"))); // NOI18N
        jLabelMangle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelMangleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelMangleMouseExited(evt);
            }
        });
        getContentPane().add(jLabelMangle);
        jLabelMangle.setBounds(40, 220, 340, 342);

        jPanelNPuesto.setBackground(new java.awt.Color(204, 255, 255));
        jPanelNPuesto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 102), 5, true));

        jLabelNPuesto.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelNPuesto.setText("Indique el número del puesto:");
        jPanelNPuesto.add(jLabelNPuesto);

        jComboNPuesto.setEditable(true);
        jComboNPuesto.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jComboNPuesto.setForeground(new java.awt.Color(204, 255, 255));
        jComboNPuesto.setEnabled(false);
        jComboNPuesto.setMaximumSize(new java.awt.Dimension(31, 22));
        jPanelNPuesto.add(jComboNPuesto);

        getContentPane().add(jPanelNPuesto);
        jPanelNPuesto.setBounds(860, 170, 270, 80);

        jPanelConfirmar.setBackground(new java.awt.Color(204, 255, 255));
        jPanelConfirmar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 102), 5, true));

        jLabelConfirmar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelConfirmar.setText("Confirmar selección:");
        jPanelConfirmar.add(jLabelConfirmar);

        jButtonConfirmar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonConfirmar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonConfirmar.setText("Confirmo");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });
        jPanelConfirmar.add(jButtonConfirmar);

        getContentPane().add(jPanelConfirmar);
        jPanelConfirmar.setBounds(730, 270, 230, 80);

        jPanelPValido.setBackground(new java.awt.Color(204, 255, 255));
        jPanelPValido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 102), 5, true));

        jLabelPValido1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelPValido1.setForeground(new java.awt.Color(255, 0, 0));
        jLabelPValido1.setText("Debe seleccionar un puesto válido");
        jPanelPValido.add(jLabelPValido1);

        jLabel3.setText(" ");
        jPanelPValido.add(jLabel3);

        jLabelPValido2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelPValido2.setForeground(new java.awt.Color(255, 0, 0));
        jLabelPValido2.setText("(desde el ? hasta el ?)");
        jPanelPValido.add(jLabelPValido2);

        getContentPane().add(jPanelPValido);
        jPanelPValido.setBounds(1140, 170, 300, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MapaCostazul.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -3, 1670, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelPalmaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPalmaMouseEntered
        jLabelCPalma.setVisible(true);
    }//GEN-LAST:event_jLabelPalmaMouseEntered

    private void jLabelPalmaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPalmaMouseExited
        jLabelCPalma.setVisible(false);
    }//GEN-LAST:event_jLabelPalmaMouseExited

    private void jLabelMangleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMangleMouseEntered
        jLabelCMangle.setVisible(true);
    }//GEN-LAST:event_jLabelMangleMouseEntered

    private void jLabelMangleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMangleMouseExited
        jLabelCMangle.setVisible(false);
    }//GEN-LAST:event_jLabelMangleMouseExited

    private void jLabelSamanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSamanMouseEntered
        jLabelCSaman.setVisible(true);
    }//GEN-LAST:event_jLabelSamanMouseEntered

    private void jLabelSamanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSamanMouseExited
        jLabelCSaman.setVisible(false);
    }//GEN-LAST:event_jLabelSamanMouseExited

    private void jLabelRobleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRobleMouseEntered
        jLabelCRoble.setVisible(true);
    }//GEN-LAST:event_jLabelRobleMouseEntered

    private void jLabelRobleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRobleMouseExited
        jLabelCRoble.setVisible(false);
    }//GEN-LAST:event_jLabelRobleMouseExited

    private void jLabelGuayacanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGuayacanMouseEntered
        jLabelCGuayacan.setVisible(true);
    }//GEN-LAST:event_jLabelGuayacanMouseEntered

    private void jLabelGuayacanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGuayacanMouseExited
        jLabelCGuayacan.setVisible(false);
    }//GEN-LAST:event_jLabelGuayacanMouseExited

    private void jLabelBambu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBambu1MouseEntered
        jLabelCBambu1.setVisible(true);
    }//GEN-LAST:event_jLabelBambu1MouseEntered

    private void jLabelBambu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBambu1MouseExited
        jLabelCBambu1.setVisible(false);
    }//GEN-LAST:event_jLabelBambu1MouseExited

    private void jLabelBambu2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBambu2MouseEntered
        jLabelCBambu2.setVisible(true);
    }//GEN-LAST:event_jLabelBambu2MouseEntered

    private void jLabelBambu2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBambu2MouseExited
        jLabelCBambu2.setVisible(false);
    }//GEN-LAST:event_jLabelBambu2MouseExited

    private void jComboSPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboSPuestoActionPerformed
        jComboNPuesto.setEnabled(true);
    }//GEN-LAST:event_jComboSPuestoActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        puestoEst puestoNuevo=null;
        
        if(jComboNPuesto.getSelectedItem().equals("") || !jComboNPuesto.getSelectedItem().toString().matches("^[0-9]+$") || Integer.parseInt(jComboNPuesto.getSelectedItem().toString())<1 || Integer.parseInt(jComboNPuesto.getSelectedItem().toString())>Integer.parseInt(jLabelPValido2.getText().substring(11, jLabelPValido2.getText().length()-1))){                       
            jPanelPValido.setVisible(true);
            jLabelPValido1.setVisible(true);
            jLabelPValido2.setVisible(true);
        } else {
            jPanelPValido.setVisible(false);
            jLabelPValido1.setVisible(false);
            jLabelPValido2.setVisible(false);
            if (esMoto){
                puestoNuevo = Bienvenido.sectoresMotos[jComboSPuesto.getSelectedIndex()][jComboNPuesto.getSelectedIndex()];
            } else{
                puestoNuevo = Bienvenido.sectoresCarros[jComboSPuesto.getSelectedIndex()][jComboNPuesto.getSelectedIndex()];
            }
            if (!puestoNuevo.getOcupantes().estaOcupado(personaActual)){
                puestoNuevo.getOcupantes().agregarPersonaAlFinal(personaActual);
                if (esMoto){
                    Bienvenido.sectoresMotos[jComboSPuesto.getSelectedIndex()][jComboNPuesto.getSelectedIndex()]=puestoNuevo;
                } else{
                    Bienvenido.sectoresCarros[jComboSPuesto.getSelectedIndex()][jComboNPuesto.getSelectedIndex()]=puestoNuevo;
                }
                int c=JOptionPane.showConfirmDialog(this, "¿Desea realizar una compra?", "Seleccione una opción:", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                dispose();
                if (c==0){
                    vCompras VC = new vCompras();
                } else{
                    if (DatosUsuario.usuariosEnSesion.getTamanio()<DatosUsuario.numUsuariosEnSesion){
                        DatosUsuario.puedeCarro=false;
                        DatosUsuario DU = new DatosUsuario();
                    } else{
                        DatosUsuario.puedeCarro=true;
                        while (!DatosUsuario.usuariosEnSesion.esVacia()){
                            Bienvenido.personas.insertarPersona(DatosUsuario.usuariosEnSesion.sacarPersonaDePila());
                    }
                        try {
                            Bienvenido B = new Bienvenido();
                            B.setVisible(true);
                        } catch (IOException ex) {
                            Logger.getLogger(DatosUsuario.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            } else{
                jPanelOcupado.setVisible(true);
                jLabelOcupado1.setVisible(true);
                jLabelOcupado2.setVisible(true);
                new Thread(){
                    public void run(){
                        try{
                            Thread.sleep(2500);
                            jPanelOcupado.setVisible(false);
                            jLabelOcupado1.setVisible(false);
                            jLabelOcupado2.setVisible(false);
                        }catch(Exception q){}
                    }
                }.start();
            }
        }
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vEstacionamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vEstacionamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vEstacionamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vEstacionamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vEstacionamiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JComboBox<String> jComboNPuesto;
    private javax.swing.JComboBox<String> jComboSPuesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelBambu1;
    private javax.swing.JLabel jLabelBambu2;
    private javax.swing.JLabel jLabelCBambu1;
    private javax.swing.JLabel jLabelCBambu2;
    private javax.swing.JLabel jLabelCGuayacan;
    private javax.swing.JLabel jLabelCMangle;
    private javax.swing.JLabel jLabelCPalma;
    private javax.swing.JLabel jLabelCRoble;
    private javax.swing.JLabel jLabelCSaman;
    private javax.swing.JLabel jLabelConfirmar;
    private javax.swing.JLabel jLabelGuayacan;
    private javax.swing.JLabel jLabelMangle;
    private javax.swing.JLabel jLabelNPuesto;
    private javax.swing.JLabel jLabelNPuestos1;
    private javax.swing.JLabel jLabelNPuestos2;
    private javax.swing.JLabel jLabelOcupado1;
    private javax.swing.JLabel jLabelOcupado2;
    private javax.swing.JLabel jLabelPValido1;
    private javax.swing.JLabel jLabelPValido2;
    private javax.swing.JLabel jLabelPalma;
    private javax.swing.JLabel jLabelRoble;
    private javax.swing.JLabel jLabelSPuesto;
    private javax.swing.JLabel jLabelSaman;
    private javax.swing.JPanel jPanelConfirmar;
    private javax.swing.JPanel jPanelInstruccion;
    private javax.swing.JPanel jPanelNPuesto;
    private javax.swing.JPanel jPanelOcupado;
    private javax.swing.JPanel jPanelPValido;
    private javax.swing.JPanel jPanelSPuesto;
    // End of variables declaration//GEN-END:variables
}
